const express = require("express");
const router = express.Router();

const db = require("../services/db");
const knowledge = require("../services/knowledge");
const liveMonitor = require("../services/liveMonitor");

function basicAuth(req, res, next) {
  const user = process.env.ADMIN_PANEL_USER;
  const pass = process.env.ADMIN_PANEL_PASSWORD;
  if (!user || !pass) {
    return res.status(503).send("Panel no configurado: define ADMIN_PANEL_USER y ADMIN_PANEL_PASSWORD.");
  }
  const header = req.headers.authorization || "";
  const [scheme, encoded] = header.split(" ");
  if (scheme === "Basic" && encoded) {
    const [u, p] = Buffer.from(encoded, "base64").toString().split(":");
    if (u === user && p === pass) return next();
  }
  res.set("WWW-Authenticate", 'Basic realm="Panel admin"');
  return res.status(401).send("Autenticación requerida.");
}

router.use(basicAuth);

router.get("/", (req, res) => {
  res.send(buildPageHtml());
});

router.get("/messages", (req, res) => {
  res.json(db.getRecentMessages(500));
});

router.get("/stream", (req, res) => {
  res.set({
    "Content-Type": "text/event-stream",
    "Cache-Control": "no-cache",
    Connection: "keep-alive",
  });
  res.flushHeaders();

  const onMessage = (row) => {
    res.write("data: " + JSON.stringify(row) + "\n\n");
  };
  liveMonitor.emitter.on("message", onMessage);

  req.on("close", () => {
    liveMonitor.emitter.off("message", onMessage);
  });
});

router.get("/knowledge", (req, res) => {
  res.json(knowledge.getAllEntries());
});

router.post("/knowledge", express.json(), (req, res) => {
  const content = (req.body?.content || "").trim();
  if (!content) return res.status(400).json({ error: "content requerido" });
  const id = knowledge.addEntry(content, "manual");
  res.json({ id });
});

router.delete("/knowledge/:id", (req, res) => {
  knowledge.deleteEntry(parseInt(req.params.id, 10));
  res.json({ ok: true });
});

router.get("/notes", (req, res) => {
  res.json(knowledge.getAllNotes());
});

router.post("/notes", express.json(), (req, res) => {
  const { title, content, tags, aliases } = req.body || {};
  const note = knowledge.createNote({
    title: (title || "").trim() || null,
    content: content || "",
    tags: tags || [],
    aliases: aliases || [],
  });
  res.json(note);
});

router.get("/notes/:id", (req, res) => {
  const note = knowledge.getNote(parseInt(req.params.id, 10));
  if (!note) return res.status(404).json({ error: "no encontrada" });
  res.json(note);
});

router.put("/notes/:id", express.json(), (req, res) => {
  const { title, content, tags, aliases } = req.body || {};
  const note = knowledge.updateNote(parseInt(req.params.id, 10), { title, content, tags, aliases });
  if (!note) return res.status(404).json({ error: "no encontrada" });
  res.json(note);
});

router.delete("/notes/:id", (req, res) => {
  knowledge.deleteEntry(parseInt(req.params.id, 10));
  res.json({ ok: true });
});

router.get("/notes/:id/versions", (req, res) => {
  res.json(knowledge.getNoteVersions(parseInt(req.params.id, 10)));
});

router.post("/notes/:id/restore/:versionId", (req, res) => {
  const note = knowledge.restoreNoteVersion(
    parseInt(req.params.id, 10),
    parseInt(req.params.versionId, 10)
  );
  if (!note) return res.status(404).json({ error: "no encontrada" });
  res.json(note);
});

router.post("/notes/daily", (req, res) => {
  res.json(knowledge.ensureDailyNote());
});

router.get("/templates", (req, res) => {
  res.json(knowledge.getAllTemplates());
});

router.post("/templates", express.json(), (req, res) => {
  const { name, content } = req.body || {};
  if (!name || !content) return res.status(400).json({ error: "name y content requeridos" });
  res.json(knowledge.addTemplate(name, content));
});

router.delete("/templates/:id", (req, res) => {
  knowledge.deleteTemplate(parseInt(req.params.id, 10));
  res.json({ ok: true });
});

router.get("/contact/:phone", (req, res) => {
  const phone = req.params.phone;
  const appointments = db.getAppointmentsByPhone(phone);
  const name = appointments.find((a) => a.client_name)?.client_name || null;
  const notes = knowledge
    .getAllEntries()
    .filter((e) => e.content.includes(phone))
    .map((e) => e.content);
  res.json({ phone, name, appointments, notes });
});

function buildPageHtml() {
  const adminPhone = process.env.ADMIN_WHATSAPP_NUMBER || "";
  return PAGE_HEAD + 'const ADMIN_PHONE = "' + adminPhone.replace(/"/g, "") + '";\n' + PAGE_SCRIPT;
}

const PAGE_HEAD = [
  "<!DOCTYPE html>",
  '<html lang="es">',
  "<head>",
  '<meta charset="utf-8" />',
  "<title>Administrador de Crea</title>",
  '<meta name="viewport" content="width=device-width, initial-scale=1" />',
  "<style>",
  "  * { box-sizing: border-box; }",
  "  body { font-family: -apple-system, BlinkMacSystemFont, 'SF Pro Text', sans-serif; margin: 0; background: #FFFFFF; color: #000000; height: 100vh; overflow: hidden; }",
  "  header { background: #1c1c1e; color: white; padding: 14px 16px; }",
  "  header .title { font-size: 16px; font-weight: 700; letter-spacing: 0.3px; }",
  "  header .subtitle { font-size: 12px; color: #A1A1A6; margin-top: 2px; }",
  "  .tabs { display: flex; background: white; border-bottom: 1px solid #E5E5EA; }",
  "  .tab { padding: 12px 20px; cursor: pointer; border-bottom: 3px solid transparent; font-size: 14px; }",
  "  .tab.active { border-bottom-color: #0A84FF; font-weight: 600; color: #0A84FF; }",
  "  .panel { display: none; }",
  "  .panel.active { display: flex; }",
  "  #live { height: calc(100vh - 124px); }",
  "",
  "  .sidebar { width: 280px; min-width: 220px; border-right: 1px solid #E5E5EA; overflow-y: auto; background: #F5F5F7; }",
  "  .contact { padding: 12px 16px; cursor: pointer; border-bottom: 1px solid #ECECEE; }",
  "  .contact:hover { background: #ECECEE; }",
  "  .contact.active { background: #E1EBFF; }",
  "  .contact .name { font-weight: 600; font-size: 14px; color: #000; }",
  "  .contact .preview { font-size: 12px; color: #8E8E93; margin-top: 2px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }",
  "  .contact .time { font-size: 11px; color: #8E8E93; float: right; }",
  "",
  "  .chat-area { flex: 1; display: flex; flex-direction: column; }",
  "  .chat-header { display: flex; align-items: center; gap: 10px; padding: 10px 16px; border-bottom: 1px solid #E5E5EA; background: #F9F9FB; }",
  "  .chat-header .user-icon-btn { width: 32px; height: 32px; border-radius: 50%; background: #C7C7CC; color: white; border: none; font-size: 16px; cursor: pointer; display: flex; align-items: center; justify-content: center; }",
  "  .chat-header .user-icon-btn:hover { background: #aeaeb2; }",
  "  .chat-header .chat-title { font-size: 14px; font-weight: 600; color: #000; }",
  "  .chat-messages { flex: 1; overflow-y: auto; padding: 16px; display: flex; flex-direction: column; }",
  "  .empty-state { margin: auto; color: #8E8E93; font-size: 14px; text-align: center; }",
  "",
  "  .modal-overlay { display: none; position: fixed; inset: 0; background: rgba(0,0,0,0.35); align-items: center; justify-content: center; z-index: 50; }",
  "  .modal-overlay.open { display: flex; }",
  "  .modal-box { background: white; border-radius: 14px; padding: 20px; width: 320px; max-width: 90vw; max-height: 80vh; overflow-y: auto; }",
  "  .modal-box h3 { margin: 0 0 12px; font-size: 16px; }",
  "  .modal-box .field { margin-bottom: 10px; }",
  "  .modal-box .field .label { font-size: 11px; color: #8E8E93; text-transform: uppercase; }",
  "  .modal-box .field .value { font-size: 14px; color: #000; margin-top: 2px; }",
  "  .modal-box .appt-item, .modal-box .note-item { font-size: 13px; padding: 6px 0; border-bottom: 1px solid #ECECEE; }",
  "  .modal-box .close-btn { margin-top: 14px; width: 100%; padding: 10px; background: #1c1c1e; color: white; border: none; border-radius: 8px; cursor: pointer; }",
  "",
  "  .bubble-row { display: flex; flex-direction: column; margin-bottom: 4px; max-width: 72%; position: relative; animation: bubbleIn 250ms cubic-bezier(0.2,0.8,0.2,1); }",
  "  .bubble-row.sent { align-self: flex-end; align-items: flex-end; }",
  "  .bubble-row.received { align-self: flex-start; align-items: flex-start; }",
  "  .bubble-row.group-start { margin-top: 12px; }",
  "",
  "  .bubble { border-radius: 22px; padding: 12px 16px; font-size: 16px; font-weight: 400; line-height: 1.35; box-shadow: 0 1px 1px rgba(0,0,0,0.05); word-wrap: break-word; }",
  "  .bubble.sent { background: #0A84FF; color: #FFFFFF; }",
  "  .bubble.received { background: #E9E9EB; color: #000000; }",
  "",
  "  .copy-btn { position: absolute; top: -10px; right: -10px; background: white; border: 1px solid #E5E5EA; border-radius: 50%; width: 22px; height: 22px; font-size: 11px; cursor: pointer; display: flex; align-items: center; justify-content: center; opacity: 0; transition: opacity 150ms; }",
  "  .bubble-row.sent:hover .copy-btn { opacity: 1; }",
  "",
  "  .timestamp { font-size: 12px; font-weight: 400; color: #8E8E93; margin-top: 4px; }",
  "",
  "  @keyframes bubbleIn { from { opacity: 0; transform: translateY(8px) scale(0.97); } to { opacity: 1; transform: translateY(0) scale(1); } }",
  "",
  '  .brain-panel { flex-direction: column; width: 100%; background: #FFFFFF; color: #111111; height: calc(100vh - 124px); overflow-y: auto; font-family: -apple-system, BlinkMacSystemFont, "SF Pro Display", sans-serif; }',
  "  .brain-inner { padding: 20px; width: 615px; max-width: 615px; margin: 0 auto; box-sizing: border-box; }",
  "  .brain-view { display: none; }",
  "  .brain-view.active { display: block; animation: brainViewIn 220ms cubic-bezier(0.2,0.8,0.2,1); }",
  "  @keyframes brainViewIn { from { opacity: 0; transform: translateY(6px); } to { opacity: 1; transform: translateY(0); } }",
  "  .brain-toolbar { display: flex; align-items: center; justify-content: space-between; margin-bottom: 16px; flex-wrap: wrap; gap: 10px; }",
  "  .brain-toolbar .view-toggle { display: flex; background: #F2F2F7; border-radius: 12px; padding: 3px; }",
  "  .brain-toolbar .view-toggle button { background: transparent; border: none; color: #6E6E73; padding: 7px 14px; border-radius: 10px; font-size: 13px; font-weight: 500; cursor: pointer; }",
  "  .brain-toolbar .view-toggle button.active { background: #FFFFFF; color: #000000; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }",
  "  .brain-capture { background: #F8F8FA; border: 1px solid #E5E5EA; border-radius: 18px; padding: 14px; margin-bottom: 18px; }",
  "  .brain-capture textarea { width: 100%; padding: 10px; border-radius: 12px; border: 1px solid #E5E5EA; background: #FFFFFF; color: #111111; font-family: inherit; font-size: 14px; resize: vertical; }",
  "  .brain-capture button.add { margin-top: 8px; padding: 9px 18px; background: #0A84FF; color: #FFFFFF; font-weight: 600; border: none; border-radius: 10px; cursor: pointer; }",
  "  .know-list { display: grid; grid-template-columns: repeat(auto-fill, minmax(240px, 1fr)); gap: 12px; }",
  "  .know-item { background: #F8F8FA; border: 1px solid #E5E5EA; border-radius: 18px; padding: 14px; display: flex; flex-direction: column; gap: 8px; }",
  "  .know-item .know-content { font-size: 13px; line-height: 1.4; color: #111111; }",
  "  .know-item .know-meta { font-size: 11px; color: #8E8E93; display: flex; justify-content: space-between; }",
  "  .know-item .know-meta .source-tag { background: #E5E5EA; padding: 2px 8px; border-radius: 8px; }",
  "  .know-item .know-meta .source-tag.auto { background: rgba(10,132,255,0.12); color: #0A84FF; }",
  "  .know-item button.del { align-self: flex-end; background: rgba(255,59,48,0.1); color: #FF3B30; border: none; border-radius: 8px; padding: 5px 10px; cursor: pointer; font-size: 12px; }",
  "  .graph-wrap { background: #F8F8FA; border: 1px solid #E5E5EA; border-radius: 18px; overflow: hidden; position: relative; height: 60vh; }",
  "  #graphCanvas { width: 100%; height: 100%; display: block; cursor: grab; }",
  "  .graph-detail { display: none; margin-top: 14px; background: #F8F8FA; border: 1px solid #E5E5EA; border-radius: 18px; padding: 14px; }",
  "  .graph-detail.open { display: block; }",
  "  .graph-detail .know-meta { font-size: 11px; color: #8E8E93; margin-bottom: 8px; }",
  "",
  "  .notes-app { display: flex; height: 70vh; border: 1px solid #E5E5EA; border-radius: 18px; overflow: hidden; }",
  "  .notes-sidebar { width: 220px; min-width: 180px; background: #F8F8FA; border-right: 1px solid #E5E5EA; display: flex; flex-direction: column; }",
  "  .notes-sidebar .ns-actions { padding: 10px; display: flex; gap: 6px; flex-wrap: wrap; }",
  "  .notes-sidebar .ns-actions button { flex: 1; background: #0A84FF; color: #fff; border: none; border-radius: 8px; padding: 7px 6px; font-size: 12px; cursor: pointer; }",
  "  .notes-sidebar .ns-actions button.secondary { background: #E5E5EA; color: #111; }",
  "  .notes-sidebar input.ns-search { margin: 0 10px 8px; padding: 7px 10px; border-radius: 8px; border: 1px solid #E5E5EA; font-size: 12px; }",
  "  .notes-sidebar .ns-list { overflow-y: auto; flex: 1; }",
  "  .ns-item { padding: 8px 12px; cursor: pointer; border-bottom: 1px solid #ECECEE; font-size: 13px; }",
  "  .ns-item:hover { background: #ECECEE; }",
  "  .ns-item.active { background: #E1EBFF; }",
  "  .ns-item .ns-title { font-weight: 600; color: #000; }",
  "  .ns-item .ns-snippet { font-size: 11px; color: #8E8E93; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }",
  "  .notes-main { flex: 1; display: flex; flex-direction: column; min-width: 0; }",
  "  .notes-tabs { display: flex; border-bottom: 1px solid #E5E5EA; overflow-x: auto; background: #FCFCFD; }",
  "  .notes-tab { padding: 8px 14px; font-size: 12px; border-right: 1px solid #ECECEE; cursor: pointer; white-space: nowrap; color: #6E6E73; }",
  "  .notes-tab.active { color: #0A84FF; font-weight: 600; background: #FFFFFF; }",
  "  .notes-tab .tab-close { margin-left: 6px; color: #C7C7CC; }",
  "  .notes-panes { flex: 1; display: flex; min-height: 0; }",
  "  .note-pane { flex: 1; display: flex; flex-direction: column; padding: 14px; overflow-y: auto; border-right: 1px solid #ECECEE; min-width: 0; }",
  "  .note-pane:last-child { border-right: none; }",
  "  .note-pane input.ns-title-input { font-size: 18px; font-weight: 700; border: none; outline: none; margin-bottom: 6px; font-family: inherit; }",
  "  .note-pane input.ns-tags-input { font-size: 12px; border: 1px solid #E5E5EA; border-radius: 8px; padding: 5px 8px; margin-bottom: 8px; font-family: inherit; }",
  "  .note-pane textarea.ns-editor { flex: 1; border: 1px solid #E5E5EA; border-radius: 10px; padding: 10px; font-size: 13px; font-family: 'SF Mono', monospace; resize: none; min-height: 180px; }",
  "  .note-pane .ns-preview { flex: 1; border: 1px solid #E5E5EA; border-radius: 10px; padding: 10px; font-size: 13px; overflow-y: auto; min-height: 180px; }",
  "  .note-pane .ns-preview h1, .note-pane .ns-preview h2, .note-pane .ns-preview h3 { margin: 6px 0; }",
  "  .note-pane .ns-preview a.wikilink { color: #0A84FF; text-decoration: none; cursor: pointer; }",
  "  .note-pane .ns-toolbar { display: flex; gap: 6px; margin-bottom: 8px; flex-wrap: wrap; }",
  "  .note-pane .ns-toolbar button { font-size: 11px; padding: 5px 9px; border-radius: 7px; border: 1px solid #E5E5EA; background: #fff; cursor: pointer; }",
  "  .note-pane .ns-backlinks { margin-top: 10px; font-size: 12px; color: #6E6E73; }",
  "  .note-pane .ns-backlinks .bl-item { padding: 3px 0; color: #0A84FF; cursor: pointer; }",
  "  .ns-empty { margin: auto; color: #8E8E93; font-size: 13px; text-align: center; }",
  "  .ns-version-item { padding: 6px 8px; border-bottom: 1px solid #ECECEE; font-size: 12px; cursor: pointer; }",
  "  .ns-version-item:hover { background: #F2F2F7; }",
  "  .tpl-item { padding: 8px; border-bottom: 1px solid #ECECEE; font-size: 13px; display: flex; justify-content: space-between; align-items: center; gap: 8px; }",
  "  .tpl-item .tpl-name { font-weight: 600; cursor: pointer; flex: 1; }",
  "  .tpl-item button { background: rgba(255,59,48,0.1); color: #FF3B30; border: none; border-radius: 8px; padding: 5px 9px; cursor: pointer; font-size: 11px; }",
  "  .modal-box input.tpl-input, .modal-box textarea.tpl-input { width: 100%; margin-top: 6px; padding: 8px; border-radius: 8px; border: 1px solid #E5E5EA; font-family: inherit; font-size: 13px; }",
  "",
  "  @media (min-width: 768px) { .bubble-row { max-width: 60%; } }",
  "  @media (min-width: 1100px) { .bubble-row { max-width: 50%; } }",
  "</style>",
  "</head>",
  "<body>",
  '<header><div class="title">ADMINISTRADOR DE CREA 📊</div><div class="subtitle">Equipo Creativo - Agencia de Marketing</div></header>',
  '<div class="tabs">',
  '  <div class="tab active" data-tab="live">💬 Mensajes</div>',
  '  <div class="tab" data-tab="brain">🧠 Segundo cerebro</div>',
  "</div>",
  "",
  '<div class="panel active" id="live">',
  '  <div class="sidebar" id="contactList"></div>',
  '  <div class="chat-area">',
  '    <div class="chat-header" id="chatHeader" style="display:none;">',
  '      <button class="user-icon-btn" id="contactInfoBtn" onclick="openContactInfo()">👤</button>',
  '      <div class="chat-title" id="chatTitle"></div>',
  "    </div>",
  '    <div class="chat-messages" id="chatMessages"><div class="empty-state">Selecciona un contacto para ver la conversación</div></div>',
  "  </div>",
  "</div>",
  "",
  '<div class="modal-overlay" id="contactModal">',
  '  <div class="modal-box" id="contactModalBody"></div>',
  "</div>",
  "",
  '<div class="panel brain-panel" id="brain">',
  '  <div class="brain-inner">',
  '    <div class="brain-toolbar">',
  '      <div class="view-toggle">',
  '        <button class="active" data-view="list" onclick="setBrainView(\'list\')">📋 Lista</button>',
  '        <button data-view="notes" onclick="setBrainView(\'notes\')">📝 Notas</button>',
  '        <button data-view="graph" onclick="setBrainView(\'graph\')">🧠 Cerebro Central</button>',
  "      </div>",
  "    </div>",
  '    <div class="brain-capture">',
  '      <textarea id="newKnowledge" rows="3" placeholder="Escribe algo para que Crea lo recuerde..."></textarea>',
  '      <button class="add" onclick="addKnowledge()">Guardar</button>',
  "    </div>",
  '    <div id="brainListView" class="brain-view active">',
  '      <div id="knowledgeList" class="know-list"></div>',
  "    </div>",
  '    <div id="brainGraphView" class="brain-view">',
  '      <div class="graph-wrap"><canvas id="graphCanvas"></canvas></div>',
  '      <div class="graph-detail" id="graphDetail"></div>',
  "    </div>",
  '    <div id="brainNotesView" class="brain-view">',
  '      <div class="notes-app">',
  '        <div class="notes-sidebar">',
  '          <div class="ns-actions">',
  '            <button onclick="createNewNote()">+ Nota</button>',
  '            <button class="secondary" onclick="openDailyNote()">📅 Hoy</button>',
  '            <button class="secondary" onclick="toggleSplitView()">⬛ Split</button>',
  '            <button class="secondary" onclick="openTemplatesModal()">📑 Plantillas</button>',
  "          </div>",
  '          <input class="ns-search" id="notesSearch" placeholder="Buscar nota..." oninput="renderNotesList()" />',
  '          <div class="ns-list" id="notesList"></div>',
  "        </div>",
  '        <div class="notes-main">',
  '          <div class="notes-tabs" id="notesTabs"></div>',
  '          <div class="notes-panes" id="notesPanes">',
  '            <div class="ns-empty" id="notesEmptyState">Selecciona o crea una nota para empezar</div>',
  "          </div>",
  "        </div>",
  "      </div>",
  "    </div>",
  "  </div>",
  "</div>",
  "",
  '<div class="modal-overlay" id="versionsModal">',
  '  <div class="modal-box" id="versionsModalBody"></div>',
  "</div>",
  "",
  '<div class="modal-overlay" id="templatesModal">',
  '  <div class="modal-box" id="templatesModalBody"></div>',
  "</div>",
  "",
  "<script>",
].join("\n");

const PAGE_SCRIPT = [
  'document.querySelectorAll(".tab").forEach(function (tab) {',
  "  tab.onclick = function () {",
  '    document.querySelectorAll(".tab").forEach(function (t) { t.classList.remove("active"); });',
  '    document.querySelectorAll(".panel").forEach(function (p) { p.classList.remove("active"); });',
  '    tab.classList.add("active");',
  "    document.getElementById(tab.dataset.tab).classList.add(\"active\");",
  "  };",
  "});",
  "",
  "var allMessages = [];",
  "var selectedPhone = null;",
  "",
  "function contactLabel(phone) {",
  '  if (phone === ADMIN_PHONE) return "Admin (tú)";',
  "  return phone;",
  "}",
  "",
  "function escapeHtml(text) {",
  '  return text.replace(/</g, "&lt;");',
  "}",
  "",
  "function formatTime(iso) {",
  '  return new Date(iso + "Z").toLocaleTimeString("es-MX", { hour: "2-digit", minute: "2-digit" });',
  "}",
  "",
  "function groupByPhone(messages) {",
  "  var map = {};",
  "  messages.forEach(function (m) {",
  "    if (!map[m.phone]) map[m.phone] = [];",
  "    map[m.phone].push(m);",
  "  });",
  "  return map;",
  "}",
  "",
  "function renderContactList() {",
  "  var grouped = groupByPhone(allMessages);",
  "  var phones = Object.keys(grouped);",
  "  phones.sort(function (a, b) {",
  "    var lastA = grouped[a][grouped[a].length - 1];",
  "    var lastB = grouped[b][grouped[b].length - 1];",
  "    return new Date(lastB.created_at) - new Date(lastA.created_at);",
  "  });",
  '  var container = document.getElementById("contactList");',
  '  container.innerHTML = "";',
  "  phones.forEach(function (phone) {",
  "    var msgs = grouped[phone];",
  "    var last = msgs[msgs.length - 1];",
  '    var div = document.createElement("div");',
  '    div.className = "contact" + (phone === selectedPhone ? " active" : "");',
  "    div.onclick = function () { selectContact(phone); };",
  '    div.innerHTML = "<div class=\\"time\\">" + formatTime(last.created_at) + "</div>" +',
  '      "<div class=\\"name\\">" + escapeHtml(contactLabel(phone)) + "</div>" +',
  '      "<div class=\\"preview\\">" + escapeHtml(last.text) + "</div>";',
  "    container.appendChild(div);",
  "  });",
  "}",
  "",
  "function renderBubble(row) {",
  '  var direction = row.direction === "out" ? "sent" : "received";',
  '  var rowDiv = document.createElement("div");',
  '  rowDiv.className = "bubble-row " + direction;',
  "",
  '  var bubble = document.createElement("div");',
  '  bubble.className = "bubble " + direction;',
  "  bubble.textContent = row.text;",
  "  rowDiv.appendChild(bubble);",
  "",
  '  if (direction === "sent") {',
  '    var copyBtn = document.createElement("button");',
  '    copyBtn.className = "copy-btn";',
  '    copyBtn.title = "Copiar mensaje";',
  '    copyBtn.textContent = "📋";',
  "    copyBtn.onclick = function (e) {",
  "      e.stopPropagation();",
  "      navigator.clipboard.writeText(row.text).then(function () {",
  '        copyBtn.textContent = "✓";',
  '        setTimeout(function () { copyBtn.textContent = "📋"; }, 1200);',
  "      });",
  "    };",
  "    rowDiv.appendChild(copyBtn);",
  "  }",
  "",
  '  var time = document.createElement("div");',
  '  time.className = "timestamp";',
  "  time.textContent = formatTime(row.created_at);",
  "  rowDiv.appendChild(time);",
  "",
  "  return rowDiv;",
  "}",
  "",
  "function selectContact(phone) {",
  "  selectedPhone = phone;",
  "  renderContactList();",
  "  renderChat();",
  '  document.getElementById("chatHeader").style.display = "flex";',
  '  document.getElementById("chatTitle").textContent = contactLabel(phone);',
  "}",
  "",
  "async function openContactInfo() {",
  "  if (!selectedPhone) return;",
  '  var res = await fetch("/admin/contact/" + selectedPhone);',
  "  var info = await res.json();",
  '  var body = document.getElementById("contactModalBody");',
  '  var html = "<h3>" + escapeHtml(contactLabel(selectedPhone)) + "</h3>";',
  '  html += "<div class=\\"field\\"><div class=\\"label\\">Número</div><div class=\\"value\\">" + escapeHtml(selectedPhone) + "</div></div>";',
  '  html += "<div class=\\"field\\"><div class=\\"label\\">Nombre</div><div class=\\"value\\">" + escapeHtml(info.name || "Sin nombre registrado") + "</div></div>";',
  '  html += "<div class=\\"field\\"><div class=\\"label\\">Citas</div>";',
  "  if (info.appointments.length === 0) {",
  '    html += "<div class=\\"value\\">Sin citas registradas</div>";',
  "  } else {",
  "    info.appointments.forEach(function (a) {",
  '      html += "<div class=\\"appt-item\\">" + escapeHtml(a.service || "Servicio") + " — " + escapeHtml(a.start_iso) + " (" + escapeHtml(a.status) + ")</div>";',
  "    });",
  "  }",
  '  html += "</div>";',
  '  html += "<div class=\\"field\\"><div class=\\"label\\">Notas del segundo cerebro</div>";',
  "  if (info.notes.length === 0) {",
  '    html += "<div class=\\"value\\">Sin notas</div>";',
  "  } else {",
  "    info.notes.forEach(function (n) {",
  '      html += "<div class=\\"note-item\\">" + escapeHtml(n) + "</div>";',
  "    });",
  "  }",
  '  html += "</div>";',
  '  html += "<button class=\\"close-btn\\" onclick=\\"closeContactInfo()\\">Cerrar</button>";',
  "  body.innerHTML = html;",
  '  document.getElementById("contactModal").classList.add("open");',
  "}",
  "",
  "function closeContactInfo() {",
  '  document.getElementById("contactModal").classList.remove("open");',
  "}",
  "",
  "function renderChat() {",
  '  var container = document.getElementById("chatMessages");',
  '  container.innerHTML = "";',
  "  if (!selectedPhone) {",
  '    container.innerHTML = "<div class=\\"empty-state\\">Selecciona un contacto para ver la conversación</div>";',
  "    return;",
  "  }",
  "  var grouped = groupByPhone(allMessages);",
  "  var msgs = grouped[selectedPhone] || [];",
  "  msgs.forEach(function (row) { container.appendChild(renderBubble(row)); });",
  "  container.scrollTop = container.scrollHeight;",
  "}",
  "",
  "async function loadMessages() {",
  '  var res = await fetch("/admin/messages");',
  "  allMessages = await res.json();",
  "  renderContactList();",
  "  renderChat();",
  "}",
  "",
  'var evtSource = new EventSource("/admin/stream");',
  "evtSource.onmessage = function (e) {",
  "  var row = JSON.parse(e.data);",
  "  allMessages.push(row);",
  "  renderContactList();",
  "  if (row.phone === selectedPhone) {",
  '    var container = document.getElementById("chatMessages");',
  "    container.appendChild(renderBubble(row));",
  "    container.scrollTop = container.scrollHeight;",
  "  }",
  "};",
  "",
"var allKnowledge = [];",
  "var brainView = \"list\";",
  "",
  "function setBrainView(view) {",
  "  brainView = view;",
  '  document.querySelectorAll(".view-toggle button").forEach(function (b) {',
  '    b.classList.toggle("active", b.dataset.view === view);',
  "  });",
  '  document.getElementById("brainListView").classList.toggle("active", view === "list");',
  '  document.getElementById("brainGraphView").classList.toggle("active", view === "graph");',
  '  document.getElementById("brainNotesView").classList.toggle("active", view === "notes");',
  "  if (view === \"graph\") {",
  "    renderGraph();",
  "  } else if (graphAnimId) {",
  "    cancelAnimationFrame(graphAnimId);",
  "    graphAnimId = null;",
  "  }",
  "  if (view === \"notes\") {",
  "    loadNotes();",
  "  }",
  "}",
  "",
  "function formatDate(iso) {",
  '  return new Date(iso + "Z").toLocaleDateString("es-MX", { day: "2-digit", month: "short" });',
  "}",
  "",
  "async function loadKnowledge() {",
  '  var res = await fetch("/admin/knowledge");',
  "  allKnowledge = await res.json();",
  '  var list = document.getElementById("knowledgeList");',
  '  list.innerHTML = "";',
  "  allKnowledge.forEach(function (row) {",
  '    var div = document.createElement("div");',
  '    div.className = "know-item";',
  "    var safeContent = escapeHtml(row.content);",
  '    var tagClass = row.source === "auto" ? "source-tag auto" : "source-tag";',
  '    var tagLabel = row.source === "auto" ? "auto" : "manual";',
  '    div.innerHTML = "<div class=\\"know-content\\">" + safeContent + "</div>" +',
  '      "<div class=\\"know-meta\\"><span class=\\"" + tagClass + "\\">" + tagLabel + "</span><span>" + formatDate(row.created_at) + "</span></div>" +',
  '      "<button class=\\"del\\" onclick=\\"deleteKnowledge(" + row.id + ")\\">Borrar</button>";',
  "    list.appendChild(div);",
  "  });",
  "  if (brainView === \"graph\") renderGraph();",
  "}",
  "",
  "async function addKnowledge() {",
  '  var textarea = document.getElementById("newKnowledge");',
  "  var content = textarea.value.trim();",
  "  if (!content) return;",
  '  await fetch("/admin/knowledge", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ content: content }) });',
  '  textarea.value = "";',
  "  loadKnowledge();",
  "}",
  "",
  "async function deleteKnowledge(id) {",
  '  await fetch("/admin/knowledge/" + id, { method: "DELETE" });',
  '  document.getElementById("graphDetail").classList.remove("open");',
  "  loadKnowledge();",
  "}",
  "",
  "var graphNodes = [];",
  "",
  "function buildGraphNodes() {",
  "  var stopwords = [\"que\", \"para\", \"con\", \"los\", \"las\", \"una\", \"uno\", \"del\", \"por\", \"sus\", \"esta\", \"esto\", \"como\"];",
  "  function keywords(text) {",
  '    return (text.toLowerCase().match(/[a-záéíóúñ0-9]{4,}/g) || []).filter(function (w) { return stopwords.indexOf(w) === -1; });',
  "  }",
  "  var nodes = allKnowledge.map(function (row, i) {",
  "    return { id: row.id, content: row.content, source: row.source, words: keywords(row.content), angle: (i / Math.max(allKnowledge.length, 1)) * Math.PI * 2 };",
  "  });",
  "  return nodes;",
  "}",
  "",
  "var graphAnimId = null;",
  "var graphDragNode = null;",
  "var graphDragMoved = false;",
  "var graphW = 0, graphH = 0;",
  "",
  "function stepPhysics(nodes) {",
  "  var repulsion = 1800;",
  "  var springLength = 110;",
  "  var springStrength = 0.02;",
  "  var damping = 0.85;",
  "  var gravity = 0.01;",
  "  var cx = graphW / 2, cy = graphH / 2;",
  "  nodes.forEach(function (n) { n.fx = 0; n.fy = 0; });",
  "  for (var i = 0; i < nodes.length; i++) {",
  "    for (var j = i + 1; j < nodes.length; j++) {",
  "      var a = nodes[i], b = nodes[j];",
  "      var dx = a.x - b.x, dy = a.y - b.y;",
  "      var dist = Math.max(Math.hypot(dx, dy), 1);",
  "      var minDist = a.r + b.r + 18;",
  "      var force = repulsion / (dist * dist);",
  "      if (dist < minDist) force += (minDist - dist) * 0.5;",
  "      var fx = (dx / dist) * force, fy = (dy / dist) * force;",
  "      a.fx += fx; a.fy += fy;",
  "      b.fx -= fx; b.fy -= fy;",
  "      var shared = a.words.some(function (w2) { return b.words.indexOf(w2) !== -1; });",
  "      if (shared) {",
  "        var sf = (dist - springLength) * springStrength;",
  "        a.fx -= (dx / dist) * sf; a.fy -= (dy / dist) * sf;",
  "        b.fx += (dx / dist) * sf; b.fy += (dy / dist) * sf;",
  "      }",
  "    }",
  "  }",
  "  nodes.forEach(function (n) {",
  "    if (n === graphDragNode) return;",
  "    n.fx += (cx - n.x) * gravity * 0.05;",
  "    n.fy += (cy - n.y) * gravity * 0.05;",
  "    n.vx = (n.vx + n.fx) * damping;",
  "    n.vy = (n.vy + n.fy) * damping;",
  "    n.x += n.vx;",
  "    n.y += n.vy;",
  "    n.x = Math.max(n.r + 10, Math.min(graphW - n.r - 10, n.x));",
  "    n.y = Math.max(n.r + 10, Math.min(graphH - n.r - 10, n.y));",
  "  });",
  "}",
  "",
  "function drawGraph(ctx, nodes, time) {",
  "  ctx.clearRect(0, 0, graphW, graphH);",
  "  ctx.strokeStyle = \"rgba(142,142,147,0.35)\";",
  "  ctx.lineWidth = 1.5;",
  "  for (var i = 0; i < nodes.length; i++) {",
  "    for (var j = i + 1; j < nodes.length; j++) {",
  "      var shared = nodes[i].words.some(function (w2) { return nodes[j].words.indexOf(w2) !== -1; });",
  "      if (shared) {",
  "        ctx.beginPath();",
  "        ctx.moveTo(nodes[i].x, nodes[i].y);",
  "        ctx.lineTo(nodes[j].x, nodes[j].y);",
  "        ctx.stroke();",
  "      }",
  "    }",
  "  }",
  "  nodes.forEach(function (n) {",
  "    var breathe = Math.sin(time * 0.0015 + n.phase) * 1.5;",
  "    var r = n.r + breathe;",
  "    ctx.beginPath();",
  "    ctx.arc(n.x, n.y, r, 0, Math.PI * 2);",
  "    ctx.fillStyle = n.source === \"auto\" ? \"#64D2FF\" : \"#0A84FF\";",
  "    ctx.fill();",
  "    ctx.font = \"11px -apple-system, sans-serif\";",
  "    ctx.fillStyle = \"#111111\";",
  "    var label = n.content.length > 18 ? n.content.slice(0, 18) + \"…\" : n.content;",
  "    ctx.fillText(label, n.x + r + 4, n.y + 4);",
  "  });",
  "}",
  "",
  "function renderGraph() {",
  '  var canvas = document.getElementById("graphCanvas");',
  "  var wrap = canvas.parentElement;",
  "  var dpr = window.devicePixelRatio || 1;",
  "  graphW = wrap.clientWidth;",
  "  graphH = wrap.clientHeight;",
  "  canvas.width = graphW * dpr;",
  "  canvas.height = graphH * dpr;",
  '  var ctx = canvas.getContext("2d");',
  "  ctx.scale(dpr, dpr);",
  "  if (graphAnimId) cancelAnimationFrame(graphAnimId);",
  "  var nodes = buildGraphNodes();",
  "  var cx = graphW / 2, cy = graphH / 2;",
  "  var radius = Math.min(graphW, graphH) / 2 - 60;",
  "  nodes.forEach(function (n) {",
  "    n.x = cx + Math.cos(n.angle) * radius * (0.3 + Math.random() * 0.7);",
  "    n.y = cy + Math.sin(n.angle) * radius * (0.3 + Math.random() * 0.7);",
  "    n.vx = 0; n.vy = 0;",
  "    n.r = n.source === \"auto\" ? 10 : 14;",
  "    n.phase = Math.random() * Math.PI * 2;",
  "  });",
  "  graphNodes = nodes;",
  "",
  "  function loop(time) {",
  "    stepPhysics(graphNodes);",
  "    drawGraph(ctx, graphNodes, time);",
  "    graphAnimId = requestAnimationFrame(loop);",
  "  }",
  "  graphAnimId = requestAnimationFrame(loop);",
  "",
  "  function nodeAt(mx, my) {",
  "    return graphNodes.find(function (n) { return Math.hypot(n.x - mx, n.y - my) <= n.r + 6; });",
  "  }",
  "",
  "  canvas.onmousedown = function (e) {",
  "    var rect = canvas.getBoundingClientRect();",
  "    var hit = nodeAt(e.clientX - rect.left, e.clientY - rect.top);",
  "    graphDragNode = hit || null;",
  "    graphDragMoved = false;",
  "  };",
  "  canvas.onmousemove = function (e) {",
  "    if (!graphDragNode) return;",
  "    var rect = canvas.getBoundingClientRect();",
  "    graphDragNode.x = e.clientX - rect.left;",
  "    graphDragNode.y = e.clientY - rect.top;",
  "    graphDragNode.vx = 0; graphDragNode.vy = 0;",
  "    graphDragMoved = true;",
  "  };",
  "  canvas.onmouseup = function (e) {",
  "    var rect = canvas.getBoundingClientRect();",
  "    var mx = e.clientX - rect.left, my = e.clientY - rect.top;",
  "    if (!graphDragMoved) {",
  "      var hit = nodeAt(mx, my);",
  '      var detail = document.getElementById("graphDetail");',
  "      if (!hit) {",
  '        detail.classList.remove("open");',
  "      } else {",
  '        var tagClass = hit.source === "auto" ? "source-tag auto" : "source-tag";',
  '        detail.innerHTML = "<div class=\\"know-meta\\"><span class=\\"" + tagClass + "\\">" + (hit.source === "auto" ? "auto" : "manual") + "</span></div>" +',
  '          "<div class=\\"know-content\\">" + escapeHtml(hit.content) + "</div>" +',
  '          "<button class=\\"del\\" style=\\"margin-top:8px;\\" onclick=\\"deleteKnowledge(" + hit.id + ")\\">Borrar</button>";',
  '        detail.classList.add("open");',
  "      }",
  "    }",
  "    graphDragNode = null;",
  "  };",
  "}",
  "",
  "window.addEventListener(\"resize\", function () { if (brainView === \"graph\") renderGraph(); });",
  "",
  "var allNotes = [];",
  "var openTabs = [];",
  "var activeTabId = null;",
  "var splitView = false;",
  "var secondTabId = null;",
  "",
  "function findNote(id) {",
  "  return allNotes.find(function (n) { return n.id === id; });",
  "}",
  "",
  "function findNoteByName(name) {",
  "  var n = name.trim().toLowerCase();",
  "  return allNotes.find(function (note) {",
  '    if ((note.title || "").trim().toLowerCase() === n) return true;',
  "    return (note.aliases || []).some(function (a) { return a.trim().toLowerCase() === n; });",
  "  });",
  "}",
  "",
  "function renderMarkdown(text) {",
  '  var html = escapeHtml(text || "");',
  '  html = html.replace(/\\[\\[([^\\]]+)\\]\\]/g, function (m, name) {',
  "    var target = findNoteByName(name);",
  '    var cls = target ? "wikilink" : "wikilink missing";',
  '    return "<a class=\\"" + cls + "\\" data-wikilink=\\"" + escapeHtml(name) + "\\">" + escapeHtml(name) + "</a>";',
  "  });",
  '  html = html.replace(/^### (.*)$/gm, "<h3>$1</h3>");',
  '  html = html.replace(/^## (.*)$/gm, "<h2>$1</h2>");',
  '  html = html.replace(/^# (.*)$/gm, "<h1>$1</h1>");',
  '  html = html.replace(/\\*\\*(.+?)\\*\\*/g, "<strong>$1</strong>");',
  '  html = html.replace(/^- (.*)$/gm, "<li>$1</li>");',
  '  html = html.replace(/(<li>.*<\\/li>)/gs, "<ul>$1</ul>");',
  '  html = html.replace(/\\n/g, "<br/>");',
  "  return html;",
  "}",
  "",
  "function handleWikilinkClick(name) {",
  "  var target = findNoteByName(name);",
  "  if (target) openNoteTab(target.id, false);",
  "}",
  "",
  'document.addEventListener("click", function (e) {',
  '  var link = e.target.closest && e.target.closest(".wikilink");',
  "  if (link) handleWikilinkClick(link.dataset.wikilink);",
  "});",
  "",
  "async function loadNotes() {",
  '  var res = await fetch("/admin/notes");',
  "  allNotes = await res.json();",
  "  renderNotesList();",
  "  renderTabs();",
  "  renderPanes();",
  "}",
  "",
  "function renderNotesList() {",
  '  var q = (document.getElementById("notesSearch").value || "").toLowerCase();',
  "  var filtered = allNotes.filter(function (n) {",
  '    return (n.title || "").toLowerCase().indexOf(q) !== -1 || (n.content || "").toLowerCase().indexOf(q) !== -1;',
  "  });",
  '  var list = document.getElementById("notesList");',
  '  list.innerHTML = "";',
  "  filtered.forEach(function (n) {",
  '    var div = document.createElement("div");',
  '    div.className = "ns-item" + (openTabs.indexOf(n.id) !== -1 && n.id === activeTabId ? " active" : "");',
  "    div.onclick = function () { openNoteTab(n.id, false); };",
  '    div.innerHTML = "<div class=\\"ns-title\\">" + escapeHtml(n.title || "Sin título") + "</div>" +',
  '      "<div class=\\"ns-snippet\\">" + escapeHtml((n.content || "").slice(0, 40)) + "</div>";',
  "    list.appendChild(div);",
  "  });",
  "}",
  "",
  "function renderTabs() {",
  '  var tabsEl = document.getElementById("notesTabs");',
  '  tabsEl.innerHTML = "";',
  "  openTabs.forEach(function (id) {",
  "    var note = findNote(id);",
  "    if (!note) return;",
  '    var tab = document.createElement("div");',
  '    tab.className = "notes-tab" + (id === activeTabId ? " active" : "");',
  "    tab.onclick = function () { activeTabId = id; renderNotesList(); renderTabs(); renderPanes(); };",
  '    tab.innerHTML = escapeHtml(note.title || "Sin título") + " <span class=\\"tab-close\\" onclick=\\"closeTab(" + id + ", event)\\">×</span>";',
  "    tabsEl.appendChild(tab);",
  "  });",
  "}",
  "",
  "function closeTab(id, event) {",
  "  if (event) event.stopPropagation();",
  "  openTabs = openTabs.filter(function (t) { return t !== id; });",
  "  if (activeTabId === id) activeTabId = openTabs.length ? openTabs[openTabs.length - 1] : null;",
  "  if (secondTabId === id) secondTabId = null;",
  "  renderNotesList();",
  "  renderTabs();",
  "  renderPanes();",
  "}",
  "",
  "function openNoteTab(id, asSecond) {",
  "  if (openTabs.indexOf(id) === -1) openTabs.push(id);",
  "  if (asSecond) { secondTabId = id; } else { activeTabId = id; }",
  "  renderNotesList();",
  "  renderTabs();",
  "  renderPanes();",
  "}",
  "",
  "function toggleSplitView() {",
  "  splitView = !splitView;",
  "  if (!splitView) secondTabId = null;",
  "  renderPanes();",
  "}",
  "",
  "function buildPaneEl(note, isPreviewMode) {",
  '  var pane = document.createElement("div");',
  '  pane.className = "note-pane";',
  "",
  '  var toolbar = document.createElement("div");',
  '  toolbar.className = "ns-toolbar";',
  '  var btnPreview = document.createElement("button");',
  '  btnPreview.textContent = isPreviewMode ? "✏️ Editar" : "👁 Vista previa";',
  "  btnPreview.onclick = function () { note._preview = !isPreviewMode; renderPanes(); };",
  '  var btnSave = document.createElement("button");',
  '  btnSave.textContent = "💾 Guardar";',
  "  btnSave.onclick = function () { saveNote(note.id, pane); };",
  '  var btnVersions = document.createElement("button");',
  '  btnVersions.textContent = "🕘 Historial";',
  "  btnVersions.onclick = function () { showVersions(note.id); };",
  '  var btnDelete = document.createElement("button");',
  '  btnDelete.textContent = "🗑 Borrar";',
  "  btnDelete.onclick = function () { deleteNote(note.id); };",
  "  toolbar.appendChild(btnPreview);",
  "  toolbar.appendChild(btnSave);",
  "  toolbar.appendChild(btnVersions);",
  "  toolbar.appendChild(btnDelete);",
  "  pane.appendChild(toolbar);",
  "",
  '  var titleInput = document.createElement("input");',
  '  titleInput.className = "ns-title-input";',
  '  titleInput.value = note.title || "";',
  '  titleInput.placeholder = "Título";',
  "  pane.appendChild(titleInput);",
  "",
  '  var tagsInput = document.createElement("input");',
  '  tagsInput.className = "ns-tags-input";',
  '  tagsInput.value = (note.tags || []).join(", ");',
  '  tagsInput.placeholder = "#tags separados por coma";',
  "  pane.appendChild(tagsInput);",
  "",
  "  if (isPreviewMode) {",
  '    var preview = document.createElement("div");',
  '    preview.className = "ns-preview";',
  "    preview.innerHTML = renderMarkdown(note.content);",
  "    pane.appendChild(preview);",
  "  } else {",
  '    var editor = document.createElement("textarea");',
  '    editor.className = "ns-editor";',
  "    editor.value = note.content || \"\";",
  "    pane.appendChild(editor);",
  "  }",
  "",
  '  var backlinksWrap = document.createElement("div");',
  '  backlinksWrap.className = "ns-backlinks";',
  '  var blTitle = document.createElement("div");',
  '  blTitle.textContent = "Backlinks:";',
  "  backlinksWrap.appendChild(blTitle);",
  "  (note.backlinks || []).forEach(function (bl) {",
  '    var blItem = document.createElement("div");',
  '    blItem.className = "bl-item";',
  '    blItem.textContent = bl.title || ("Nota #" + bl.id);',
  "    blItem.onclick = function () { openNoteTab(bl.id, false); };",
  "    backlinksWrap.appendChild(blItem);",
  "  });",
  "  if (!note.backlinks || note.backlinks.length === 0) {",
  '    var none = document.createElement("div");',
  '    none.textContent = "Ninguno";',
  '    none.style.color = "#C7C7CC";',
  "    backlinksWrap.appendChild(none);",
  "  }",
  "  pane.appendChild(backlinksWrap);",
  "",
  "  pane._titleInput = titleInput;",
  "  pane._tagsInput = tagsInput;",
  "  pane._noteId = note.id;",
  "  return pane;",
  "}",
  "",
  "function renderPanes() {",
  '  var panesEl = document.getElementById("notesPanes");',
  '  panesEl.innerHTML = "";',
  "  if (!activeTabId) {",
  '    var empty = document.createElement("div");',
  '    empty.className = "ns-empty";',
  '    empty.textContent = "Selecciona o crea una nota para empezar";',
  "    panesEl.appendChild(empty);",
  "    return;",
  "  }",
  "  var note1 = findNote(activeTabId);",
  "  if (note1) panesEl.appendChild(buildPaneEl(note1, !!note1._preview));",
  "  if (splitView && secondTabId) {",
  "    var note2 = findNote(secondTabId);",
  "    if (note2) panesEl.appendChild(buildPaneEl(note2, !!note2._preview));",
  "  }",
  "}",
  "",
  "async function saveNote(id, pane) {",
  "  var title = pane._titleInput.value.trim();",
  '  var tags = pane._tagsInput.value.split(",").map(function (t) { return t.trim(); }).filter(Boolean);',
  '  var editor = pane.querySelector(".ns-editor");',
  "  var content = editor ? editor.value : findNote(id).content;",
  '  await fetch("/admin/notes/" + id, {',
  '    method: "PUT",',
  '    headers: { "Content-Type": "application/json" },',
  "    body: JSON.stringify({ title: title, content: content, tags: tags }),",
  "  });",
  "  await loadNotes();",
  "}",
  "",
  "async function deleteNote(id) {",
  '  await fetch("/admin/notes/" + id, { method: "DELETE" });',
  "  closeTab(id, null);",
  "  await loadNotes();",
  "}",
  "",
  "async function createNewNote() {",
  '  var res = await fetch("/admin/notes", {',
  '    method: "POST",',
  '    headers: { "Content-Type": "application/json" },',
  '    body: JSON.stringify({ title: "Nueva nota", content: "" }),',
  "  });",
  "  var note = await res.json();",
  "  await loadNotes();",
  "  openNoteTab(note.id, false);",
  "}",
  "",
  "async function openDailyNote() {",
  '  var res = await fetch("/admin/notes/daily", { method: "POST" });',
  "  var note = await res.json();",
  "  await loadNotes();",
  "  openNoteTab(note.id, false);",
  "}",
  "",
  "async function showVersions(id) {",
  '  var res = await fetch("/admin/notes/" + id + "/versions");',
  "  var versions = await res.json();",
  '  var body = document.getElementById("versionsModalBody");',
  '  var html = "<h3>Historial de versiones</h3>";',
  "  if (versions.length === 0) {",
  '    html += "<div class=\\"value\\">Sin versiones anteriores</div>";',
  "  } else {",
  "    versions.forEach(function (v) {",
  '      html += "<div class=\\"ns-version-item\\" onclick=\\"restoreVersion(" + id + ", " + v.id + ")\\">" +',
  '        escapeHtml(formatDate(v.created_at)) + " — " + escapeHtml((v.content || "").slice(0, 50)) + "</div>";',
  "    });",
  "  }",
  '  html += "<button class=\\"close-btn\\" onclick=\\"closeVersionsModal()\\">Cerrar</button>";',
  "  body.innerHTML = html;",
  '  document.getElementById("versionsModal").classList.add("open");',
  "}",
  "",
  "function closeVersionsModal() {",
  '  document.getElementById("versionsModal").classList.remove("open");',
  "}",
  "",
  "async function restoreVersion(id, versionId) {",
  '  await fetch("/admin/notes/" + id + "/restore/" + versionId, { method: "POST" });',
  "  closeVersionsModal();",
  "  await loadNotes();",
  "  renderPanes();",
  "}",
  "",
  "async function openTemplatesModal() {",
  '  var res = await fetch("/admin/templates");',
  "  var templates = await res.json();",
  '  var body = document.getElementById("templatesModalBody");',
  '  var html = "<h3>Plantillas reutilizables</h3>";',
  "  if (templates.length === 0) {",
  '    html += "<div class=\\"value\\">Sin plantillas todavía</div>";',
  "  } else {",
  "    templates.forEach(function (t) {",
  '      html += "<div class=\\"tpl-item\\"><span class=\\"tpl-name\\" onclick=\\"useTemplate(" + t.id + ")\\">" + escapeHtml(t.name) + "</span>" +',
  '        "<button onclick=\\"deleteTemplateAndRefresh(" + t.id + ")\\">Borrar</button></div>";',
  "    });",
  "  }",
  '  html += "<input class=\\"tpl-input\\" id=\\"newTplName\\" placeholder=\\"Nombre de la plantilla\\" />";',
  '  html += "<textarea class=\\"tpl-input\\" id=\\"newTplContent\\" rows=\\"4\\" placeholder=\\"Contenido de la plantilla\\"></textarea>";',
  '  html += "<button class=\\"close-btn\\" style=\\"background:#0A84FF; margin-top:8px;\\" onclick=\\"saveNewTemplate()\\">Guardar plantilla</button>";',
  '  html += "<button class=\\"close-btn\\" onclick=\\"closeTemplatesModal()\\">Cerrar</button>";',
  "  body.innerHTML = html;",
  '  document.getElementById("templatesModal").classList.add("open");',
  "}",
  "",
  "function closeTemplatesModal() {",
  '  document.getElementById("templatesModal").classList.remove("open");',
  "}",
  "",
  "async function saveNewTemplate() {",
  '  var name = document.getElementById("newTplName").value.trim();',
  '  var content = document.getElementById("newTplContent").value;',
  "  if (!name || !content) return;",
  '  await fetch("/admin/templates", {',
  '    method: "POST",',
  '    headers: { "Content-Type": "application/json" },',
  "    body: JSON.stringify({ name: name, content: content }),",
  "  });",
  "  await openTemplatesModal();",
  "}",
  "",
  "async function deleteTemplateAndRefresh(id) {",
  '  await fetch("/admin/templates/" + id, { method: "DELETE" });',
  "  await openTemplatesModal();",
  "}",
  "",
  "async function useTemplate(id) {",
  '  var res = await fetch("/admin/templates");',
  "  var templates = await res.json();",
  "  var tpl = templates.find(function (t) { return t.id === id; });",
  "  if (!tpl) return;",
  '  var res2 = await fetch("/admin/notes", {',
  '    method: "POST",',
  '    headers: { "Content-Type": "application/json" },',
  "    body: JSON.stringify({ title: tpl.name, content: tpl.content }),",
  "  });",
  "  var note = await res2.json();",
  "  closeTemplatesModal();",
  "  await loadNotes();",
  "  openNoteTab(note.id, false);",
  "}",
  "",
  "loadMessages();",
  "loadKnowledge();",
  "</script>",
  "</body>",
  "</html>",
].join("\n");

module.exports = router;
