const express = require("express");
const router = express.Router();

const path = require("path");
const crypto = require("crypto");
const multer = require("multer");
const db = require("../services/db");
const knowledge = require("../services/knowledge");
const liveMonitor = require("../services/liveMonitor");
const files = require("../services/files");

const upload = multer({
  storage: multer.diskStorage({
    destination: (req, file, cb) => cb(null, files.uploadsDir),
    filename: (req, file, cb) => {
      const unique = crypto.randomBytes(8).toString("hex");
      cb(null, unique + path.extname(file.originalname).toLowerCase());
    },
  }),
  limits: { fileSize: 25 * 1024 * 1024 },
  fileFilter: (req, file, cb) => {
    if (!files.isAllowedFile(file.originalname)) {
      return cb(new Error("Tipo de archivo no permitido. Solo PDF, Word, Excel, Imagen o VCF."));
    }
    cb(null, true);
  },
});

function basicAuth(req, res, next) {
  const user = process.env.ADMIN_PANEL_USER;
  const pass = process.env.ADMIN_PANEL_PASSWORD;
  if (!user || !pass) {
    return res.status(503).send("Panel no configurado: define ADMIN_PANEL_USER y ADMIN_PANEL_PASSWORD.");
  }
  const header = req.headers.authorization || "";
  const [scheme, encoded] = header.split(" ");
  if (scheme === "Basic" && encoded) {
    const [u, p] = Buffer.from(encoded, "base64").toString().split(":");
    if (u === user && p === pass) return next();
  }
  res.set("WWW-Authenticate", 'Basic realm="Panel admin"');
  return res.status(401).send("Autenticación requerida.");
}

router.use(basicAuth);
router.use("/assets", express.static(path.join(__dirname, "..", "..", "public", "assets")));

router.get("/", (req, res) => {
  res.send(buildPageHtml());
});

router.get("/messages", (req, res) => {
  res.json(db.getRecentMessages(500));
});

router.get("/stream", (req, res) => {
  res.set({
    "Content-Type": "text/event-stream",
    "Cache-Control": "no-cache",
    Connection: "keep-alive",
  });
  res.flushHeaders();

  const onMessage = (row) => {
    res.write("data: " + JSON.stringify(row) + "\n\n");
  };
  liveMonitor.emitter.on("message", onMessage);

  req.on("close", () => {
    liveMonitor.emitter.off("message", onMessage);
  });
});

router.get("/knowledge", (req, res) => {
  const entries = knowledge.getAllEntries();
  // Backfill missing titles synchronously (fast heuristic, no API call)
  for (const e of entries) {
    if (!e.title) {
      const t = knowledge.autoTitle(e.content);
      if (t) {
        db.db.prepare("UPDATE knowledge SET title = ? WHERE id = ?").run(t, e.id);
        e.title = t;
      }
    }
  }
  res.json(entries);
});

router.get("/hub-notes", (req, res) => {
  const hubs = knowledge.getAllNotes().filter((n) =>
    (n.tags || []).includes("plantilla-hub")
  );
  const hubTitles = new Set(hubs.map((n) => (n.title || "").toLowerCase().trim()));
  const templates = knowledge.getAllTemplates();
  const extra = templates
    .filter((t) => !hubTitles.has((t.name || "").toLowerCase().trim()))
    .map((t) => ({ id: "tpl_" + t.id, title: t.name, content: "" }));
  const result = hubs
    .map((n) => ({ id: n.id, title: n.title || "", content: n.content || "" }))
    .concat(extra);
  res.json(result);
});

router.get("/stats", (req, res) => {
  const business = require("../config/business");
  const allMessages = db.getRecentMessages(5000);
  const incoming = allMessages.filter((m) => m.direction === "in");

  const totalMessages = allMessages.length;

  const hourCounts = new Array(24).fill(0);
  incoming.forEach((m) => {
    const h = new Date(m.created_at + "Z").getUTCHours();
    hourCounts[h] += 1;
  });
  let peakHour = 0;
  hourCounts.forEach((c, h) => {
    if (c > hourCounts[peakHour]) peakHour = h;
  });

  const uniqueContacts = new Set(incoming.map((m) => m.phone));
  const appointments = db.getAllUpcomingConfirmedAppointments();
  const allApptPhones = new Set(
    db.db.prepare("SELECT DISTINCT phone FROM appointments").all().map((r) => r.phone)
  );
  const contactsWithAppointment = [...uniqueContacts].filter((p) => allApptPhones.has(p));
  const bookedRatio = uniqueContacts.size
    ? Math.round((contactsWithAppointment.length / uniqueContacts.size) * 100)
    : 0;

  const productNames = (business.servicios || [])
    .map((s) => s.nombre)
    .concat(business.serviciosCotizacion || []);
  const productCounts = productNames.map((name) => {
    const keyword = name.split("(")[0].trim().split(" ").slice(0, 2).join(" ").toLowerCase();
    const count = incoming.filter((m) => (m.text || "").toLowerCase().includes(keyword)).length;
    return { name, count };
  }).filter((p) => p.count > 0).sort((a, b) => b.count - a.count);

  res.json({
    totalMessages,
    totalIncoming: incoming.length,
    peakHour,
    hourCounts,
    uniqueContacts: uniqueContacts.size,
    bookedContacts: contactsWithAppointment.length,
    bookedRatio,
    upcomingAppointments: appointments.length,
    topProducts: productCounts.slice(0, 6),
  });
});

router.get("/auto-clusters", (req, res) => {
  const allEntries = knowledge.getAllEntries();
  const clientEntries = allEntries.filter((e) => /^Cliente:/i.test(e.content || ""));
  const entries = allEntries.filter((e) => !/^Cliente:/i.test(e.content || ""));

  const clusters = [];
  if (clientEntries.length) {
    clusters.push({
      name: "Clientes",
      keyword: "cliente",
      noteIds: clientEntries.map((e) => e.id),
    });
  }

  const stop = new Set([
    "que","para","con","los","las","una","uno","del","por","sus","esta","esto","como","tiene",
    "pero","hace","muy","mas","son","fue","han","van","sin","hay","ser","este","eres","todo",
    "cada","cuando","donde","aqui","sobre","desde","hasta","entre","tambien","solo","bien",
    "parte","debe","puede","pueden","tiene","tener","haber","sido","sido","seran","sera",
    "crea","equipo","creativo","nota","notes",
  ]);
  // Count keyword frequency across all entries
  const freq = {};
  for (const e of entries) {
    const words = ((e.content || "") + " " + (e.title || ""))
      .toLowerCase().match(/[a-zà-ÿ]{4,}/g) || [];
    const unique = [...new Set(words.filter((w) => !stop.has(w)))];
    for (const w of unique) freq[w] = (freq[w] || 0) + 1;
  }
  // Top keywords appearing in ≥2 notes
  const topWords = Object.entries(freq)
    .filter(([, c]) => c >= 2)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 7)
    .map(([w]) => w);

  topWords.forEach((word) => {
    const noteIds = entries
      .filter((e) => ((e.content || "") + " " + (e.title || "")).toLowerCase().includes(word))
      .map((e) => e.id);
    if (noteIds.length >= 2) {
      clusters.push({
        name: word.charAt(0).toUpperCase() + word.slice(1),
        keyword: word,
        noteIds,
      });
    }
  });

  res.json(clusters);
});

router.post("/knowledge", express.json({ limit: "15mb" }), async (req, res) => {
  let content = (req.body?.content || "").trim();
  if (!content) return res.status(400).json({ error: "content requerido" });
  // Auto-tag: classify against existing templates if no hashtag already present
  if (!content.startsWith("#")) {
    try {
      const templates = knowledge.getAllTemplates();
      if (templates.length > 0) {
        const names = templates.map((t) => t.name).join(", ");
        const Anthropic = require("@anthropic-ai/sdk");
        const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
        const resp = await anthropic.messages.create({
          model: "claude-sonnet-4-6",
          max_tokens: 30,
          messages: [{
            role: "user",
            content: `Categorías disponibles: ${names}.\nNota: "${content}"\n¿A cuál categoría pertenece esta nota? Responde SOLO con el nombre exacto de la categoría (sin comillas, sin explicación). Si no encaja en ninguna, responde NONE.`,
          }],
        });
        const cat = (resp.content[0].text || "").trim();
        if (cat && cat !== "NONE" && templates.some((t) => t.name.toLowerCase() === cat.toLowerCase())) {
          const match = templates.find((t) => t.name.toLowerCase() === cat.toLowerCase());
          content = "#" + match.name.replace(/\s+/g, "") + " " + content;
        }
      }
    } catch (e) {
      console.error("auto-tag error:", e.message);
    }
  }
  const id = knowledge.addEntry(content, "manual");
  res.json({ id });
});

router.delete("/knowledge/:id", (req, res) => {
  knowledge.deleteEntry(parseInt(req.params.id, 10));
  res.json({ ok: true });
});

router.put("/knowledge/:id", express.json({ limit: "15mb" }), (req, res) => {
  const content = (req.body?.content || "").trim();
  if (!content) return res.status(400).json({ error: "content requerido" });
  knowledge.updateEntry(parseInt(req.params.id, 10), content);
  res.json({ ok: true });
});

function sanitizeForJson(str) {
  if (typeof str !== "string") return str;
  // Remove NUL bytes and other characters that break JSON serialization
  return str.replace(/ /g, "").replace(/[\x01-\x08\x0B\x0C\x0E-\x1F\x7F]/g, "");
}

function sanitizeNote(note) {
  if (!note) return note;
  return { ...note, content: sanitizeForJson(note.content), title: sanitizeForJson(note.title) };
}

router.get("/notes", (req, res) => {
  try {
    res.json(knowledge.getAllNotes().map(sanitizeNote));
  } catch (err) {
    console.error("Error serializando notas:", err);
    res.status(500).json({ error: "Error al cargar notas: " + err.message });
  }
});

// Dedicated endpoint to find-or-create a hub note for a template and append an entry.
// Avoids sending all notes to client and sidesteps any serialization issues.
router.post("/hub-save", express.json({ limit: "15mb" }), (req, res) => {
  try {
    const { templateName, entryContent } = req.body || {};
    if (!templateName || !entryContent) {
      return res.status(400).json({ error: "templateName y entryContent requeridos" });
    }
    const allNotes = knowledge.getAllNotes();
    let hub = allNotes.find(
      (n) =>
        (n.tags || []).includes("plantilla-hub") &&
        (n.title || "").toLowerCase() === templateName.toLowerCase()
    );
    if (!hub) {
      hub = knowledge.createNote({
        title: templateName,
        content: "",
        tags: [templateName, "plantilla-hub"],
        source: "manual",
      });
    }
    const stamp = new Date().toLocaleString("es-MX");
    const currentContent = sanitizeForJson(hub.content || "");
    const appended = (currentContent ? currentContent + "\n\n---\n" : "") + "[" + stamp + "] " + entryContent;
    knowledge.updateNote(hub.id, { content: appended });
    const hashtag = "#" + templateName.replace(/\s+/g, "");
    knowledge.addEntry(hashtag + " " + entryContent, "manual");
    res.json({ ok: true });
  } catch (err) {
    console.error("Error en hub-save:", err);
    res.status(500).json({ error: err.message || "Error desconocido" });
  }
});

router.post("/notes", express.json({ limit: "15mb" }), (req, res) => {
  const { title, content, tags, aliases } = req.body || {};
  const note = knowledge.createNote({
    title: (title || "").trim() || null,
    content: content || "",
    tags: tags || [],
    aliases: aliases || [],
  });
  res.json(note);
});

router.get("/notes/:id", (req, res) => {
  const note = knowledge.getNote(parseInt(req.params.id, 10));
  if (!note) return res.status(404).json({ error: "no encontrada" });
  res.json(note);
});

router.put("/notes/:id", express.json({ limit: "15mb" }), (req, res) => {
  const { title, content, tags, aliases } = req.body || {};
  const note = knowledge.updateNote(parseInt(req.params.id, 10), { title, content, tags, aliases });
  if (!note) return res.status(404).json({ error: "no encontrada" });
  res.json(note);
});

router.delete("/notes/:id", (req, res) => {
  knowledge.deleteEntry(parseInt(req.params.id, 10));
  res.json({ ok: true });
});

router.get("/notes/:id/versions", (req, res) => {
  res.json(knowledge.getNoteVersions(parseInt(req.params.id, 10)));
});

router.post("/notes/:id/restore/:versionId", (req, res) => {
  const note = knowledge.restoreNoteVersion(
    parseInt(req.params.id, 10),
    parseInt(req.params.versionId, 10)
  );
  if (!note) return res.status(404).json({ error: "no encontrada" });
  res.json(note);
});

router.post("/notes/daily", (req, res) => {
  res.json(knowledge.ensureDailyNote());
});

router.get("/templates", (req, res) => {
  res.json(knowledge.getAllTemplates());
});

router.post("/templates", express.json({ limit: "15mb" }), (req, res) => {
  const { name, content } = req.body || {};
  if (!name || !content) return res.status(400).json({ error: "name y content requeridos" });
  res.json(knowledge.addTemplate(name, content));
});

router.delete("/templates/:id", (req, res) => {
  knowledge.deleteTemplate(parseInt(req.params.id, 10));
  res.json({ ok: true });
});

router.post("/files/upload", (req, res) => {
  upload.single("file")(req, res, async (err) => {
    if (err) return res.status(400).json({ error: err.message });
    if (!req.file) return res.status(400).json({ error: "No se recibió ningún archivo" });
    const result = await files.processUploadedFile({
      originalName: req.file.originalname,
      storedName: req.file.filename,
      mimeType: req.file.mimetype,
      size: req.file.size,
    });
    res.json(result);
  });
});

router.get("/files", (req, res) => {
  res.json(files.getAllFiles());
});

router.get("/files/:id", (req, res) => {
  const file = files.getFile(parseInt(req.params.id, 10));
  if (!file) return res.status(404).json({ error: "No encontrado" });
  res.json(file);
});

router.delete("/files/:id", (req, res) => {
  files.deleteFile(parseInt(req.params.id, 10));
  res.json({ ok: true });
});

router.get("/contact/:phone", (req, res) => {
  const phone = req.params.phone;
  const appointments = db.getAppointmentsByPhone(phone);
  const name = appointments.find((a) => a.client_name)?.client_name || null;
  const notes = knowledge
    .getAllEntries()
    .filter((e) => e.content.includes(phone))
    .map((e) => e.content);
  res.json({ phone, name, appointments, notes });
});

function buildPageHtml() {
  const adminPhone = process.env.ADMIN_WHATSAPP_NUMBER || "";
  const phoneSafe = adminPhone.replace(/"/g, "");
  return PAGE_HEAD.replace('<script>\n', '<script>\nconst ADMIN_PHONE = "' + phoneSafe + '";\n');
}

const PAGE_HEAD = [
  "<!DOCTYPE html>",
  '<html lang="es">',
  "<head>",
  '<meta charset="utf-8" />',
  "<title>Administrador de Crea</title>",
  '<meta name="viewport" content="width=device-width, initial-scale=1" />',
  "<style>",
  "  * { box-sizing: border-box; }",
  "  :root { --blue:#3E6BF5; --blue-soft:#EAF0FE; --bg:#F2F5FC; --black:#14161A; --yellow:#FFD84D; --card:#FFFFFF; --line:#E7ECF6; }",
  "  body { font-family: -apple-system, BlinkMacSystemFont, 'SF Pro Text', sans-serif; margin: 0; background: var(--bg); color: var(--black); height: 100vh; overflow: hidden; }",
  "  .app-shell { display: block; height: 100vh; position: relative; }",
  "  .app-sidebar { position: absolute; top: 28px; left: 24px; z-index: 230; display: flex; flex-direction: column; align-items: center; gap: 16px; background: transparent; padding: 0; width: auto; }",
  "  .app-sidebar .logo { width: 30px; height: 30px; object-fit: contain; background: #FFFFFF; border-radius: 14px; padding: 6px; box-shadow: 0 4px 16px rgba(20,22,26,0.10); margin-bottom: 10px; }",
  "  .app-sidebar .nav-item { position: relative; width: 46px; height: 46px; border-radius: 50%; display: flex; align-items: center; justify-content: center; cursor: pointer; color: #14161A; background: #FFFFFF; box-shadow: 0 4px 14px rgba(20,22,26,0.08); }",
  "  .app-sidebar .nav-item .ic { font-size: 17px; }",
  "  .app-sidebar .nav-item:hover { color: var(--blue); }",
  "  .app-sidebar .nav-item.active { background: var(--black); color: #FFFFFF; }",
  "  .app-sidebar .nav-item .nav-label { display: none; position: absolute; left: 58px; top: 50%; transform: translateY(-50%); background: var(--black); color: #FFFFFF; padding: 7px 14px; border-radius: 10px; font-size: 12px; font-weight: 600; white-space: nowrap; box-shadow: 0 4px 14px rgba(20,22,26,0.18); }",
  "  .app-sidebar .nav-item:hover .nav-label { display: block; }",
  "  .app-main { height: 100%; display: flex; flex-direction: column; min-width: 0; padding-left: 90px; }",
  "  header { background: transparent; color: var(--black); padding: 24px 28px 16px; position: relative; z-index: 210; border-bottom: none; }",
  "  header .title { font-size: 16px; font-weight: 800; letter-spacing: 0.2px; }",
  "  header .subtitle { font-size: 12px; color: #8A93A6; margin-top: 2px; }",
  "  .tabs { display: none; }",
  "  .panel { display: none; }",
  "  .panel.active { display: flex; flex: 1; min-height: 0; }",
  "",
  "  .sidebar { width: 280px; min-width: 220px; border-right: 1px solid #E5E5EA; overflow-y: auto; background: #F5F5F7; }",
  "  .contact { padding: 12px 16px; cursor: pointer; border-bottom: 1px solid #ECECEE; }",
  "  .contact:hover { background: #ECECEE; }",
  "  .contact.active { background: #E1EBFF; }",
  "  .contact .name { font-weight: 600; font-size: 14px; color: #000; }",
  "  .contact .preview { font-size: 12px; color: #8E8E93; margin-top: 2px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }",
  "  .contact .time { font-size: 11px; color: #8E8E93; float: right; }",
  "",
  "  .chat-area { flex: 1; display: flex; flex-direction: column; }",
  "  .chat-header { display: flex; align-items: center; gap: 10px; padding: 10px 16px; border-bottom: 1px solid #E5E5EA; background: #F9F9FB; }",
  "  .chat-header .user-icon-btn { width: 32px; height: 32px; border-radius: 50%; background: #C7C7CC; color: white; border: none; font-size: 16px; cursor: pointer; display: flex; align-items: center; justify-content: center; }",
  "  .chat-header .user-icon-btn:hover { background: #aeaeb2; }",
  "  .chat-header .chat-title { font-size: 14px; font-weight: 600; color: #000; }",
  "  .chat-messages { flex: 1; overflow-y: auto; padding: 16px; display: flex; flex-direction: column; }",
  "  .empty-state { margin: auto; color: #8E8E93; font-size: 14px; text-align: center; }",
  "",
  "  .modal-overlay { display: none; position: fixed; inset: 0; background: rgba(0,0,0,0.35); align-items: center; justify-content: center; z-index: 50; }",
  "  .modal-overlay.open { display: flex; }",
  "  .modal-box { background: white; border-radius: 14px; padding: 20px; width: 320px; max-width: 90vw; max-height: 80vh; overflow-y: auto; }",
  "  .modal-box h3 { margin: 0 0 12px; font-size: 16px; }",
  "  .modal-box .field { margin-bottom: 10px; }",
  "  .modal-box .field .label { font-size: 11px; color: #8E8E93; text-transform: uppercase; }",
  "  .modal-box .field .value { font-size: 14px; color: #000; margin-top: 2px; }",
  "  .modal-box .appt-item, .modal-box .note-item { font-size: 13px; padding: 6px 0; border-bottom: 1px solid #ECECEE; }",
  "  .modal-box .close-btn { margin-top: 14px; width: 100%; padding: 10px; background: #1c1c1e; color: white; border: none; border-radius: 8px; cursor: pointer; }",
  "",
  "  .bubble-row { display: flex; flex-direction: column; margin-bottom: 4px; max-width: 72%; position: relative; animation: bubbleIn 250ms cubic-bezier(0.2,0.8,0.2,1); }",
  "  .bubble-row.sent { align-self: flex-end; align-items: flex-end; }",
  "  .bubble-row.received { align-self: flex-start; align-items: flex-start; }",
  "  .bubble-row.group-start { margin-top: 12px; }",
  "",
  "  .bubble { border-radius: 22px; padding: 12px 16px; font-size: 16px; font-weight: 400; line-height: 1.35; box-shadow: 0 1px 1px rgba(0,0,0,0.05); word-wrap: break-word; }",
  "  .bubble.sent { background: #0A84FF; color: #FFFFFF; }",
  "  .bubble.received { background: #E9E9EB; color: #000000; }",
  "",
  "  .copy-btn { position: absolute; top: -10px; right: -10px; background: white; border: 1px solid #E5E5EA; border-radius: 50%; width: 22px; height: 22px; font-size: 11px; cursor: pointer; display: flex; align-items: center; justify-content: center; opacity: 0; transition: opacity 150ms; }",
  "  .bubble-row.sent:hover .copy-btn { opacity: 1; }",
  "",
  "  .timestamp { font-size: 12px; font-weight: 400; color: #8E8E93; margin-top: 4px; }",
  "",
  "  @keyframes bubbleIn { from { opacity: 0; transform: translateY(8px) scale(0.97); } to { opacity: 1; transform: translateY(0) scale(1); } }",
  "",
  '  .brain-panel { flex-direction: column; width: 100%; background: #FFFFFF; color: #111111; overflow-y: auto; font-family: -apple-system, BlinkMacSystemFont, "SF Pro Display", sans-serif; }',
  "  .brain-inner { padding: 20px; width: 615px; max-width: 615px; margin: 0 auto; box-sizing: border-box; }",
  "  .brain-view { display: none; }",
  "  .brain-view.active { display: block; animation: brainViewIn 220ms cubic-bezier(0.2,0.8,0.2,1); }",
  "  @keyframes brainViewIn { from { opacity: 0; transform: translateY(6px); } to { opacity: 1; transform: translateY(0); } }",
  "  .brain-toolbar { display: flex; align-items: center; justify-content: space-between; margin-bottom: 16px; flex-wrap: wrap; gap: 10px; }",
  "  .brain-toolbar .view-toggle { display: flex; background: var(--blue-soft); border-radius: 20px; padding: 5px; }",
  "  .brain-toolbar .view-toggle button { background: transparent; border: none; color: var(--blue); padding: 9px 18px; border-radius: 16px; font-size: 14px; font-weight: 600; cursor: pointer; }",
  "  .brain-toolbar .view-toggle button.active { background: #FFFFFF; color: var(--black); box-shadow: 0 2px 8px rgba(0,0,0,0.08); }",
  "  .brain-capture { background: #F8F8FA; border: 1px solid #E5E5EA; border-radius: 18px; padding: 14px; margin-bottom: 18px; }",
  "  .brain-capture textarea { width: 100%; padding: 10px; border-radius: 12px; border: 1px solid #E5E5EA; background: #FFFFFF; color: #111111; font-family: inherit; font-size: 14px; resize: vertical; }",
  "  .brain-capture button.add { padding: 9px 18px; background: #0A84FF; color: #FFFFFF; font-weight: 600; border: none; border-radius: 10px; cursor: pointer; }",
  "  .capture-actions { display: flex; align-items: center; justify-content: space-between; margin-top: 8px; }",
  "  .capture-plus-wrap { position: relative; }",
  "  .capture-plus { width: 32px; height: 32px; border-radius: 50%; background: #E5E5EA; color: #111111; border: none; font-size: 18px; font-weight: 700; cursor: pointer; line-height: 1; }",
  "  .capture-menu { display: none; position: absolute; bottom: 38px; left: 0; background: #FFFFFF; border: 1px solid #E5E5EA; border-radius: 12px; box-shadow: 0 8px 24px rgba(0,0,0,0.12); min-width: 200px; z-index: 20; overflow: hidden; }",
  "  .capture-menu.open { display: block; }",
  "  .capture-menu-item { padding: 10px 14px; font-size: 13px; cursor: pointer; white-space: nowrap; }",
  "  .capture-menu-item:hover { background: #F2F2F7; }",
  "  .capture-tpl-badge { display: inline-flex; align-items: center; gap: 6px; background: rgba(10,132,255,0.12); color: #0A84FF; font-size: 12px; font-weight: 600; padding: 5px 10px; border-radius: 20px; margin-bottom: 8px; }",
  "  .capture-tpl-badge .x { cursor: pointer; font-weight: 700; }",
  "  .know-list { display: grid; grid-template-columns: repeat(auto-fill, minmax(240px, 1fr)); gap: 12px; }",
  "  .know-item { background: #F8F8FA; border: 1px solid #E5E5EA; border-radius: 18px; padding: 14px; display: flex; flex-direction: column; gap: 8px; }",
  "  .know-item .know-content { font-size: 13px; line-height: 1.4; color: #111111; }",
  "  .know-item .know-meta { font-size: 11px; color: #8E8E93; display: flex; justify-content: space-between; }",
  "  .know-item .know-meta .source-tag { background: #E5E5EA; padding: 2px 8px; border-radius: 8px; }",
  "  .know-item .know-meta .source-tag.auto { background: rgba(10,132,255,0.12); color: #0A84FF; }",
  "  .know-item button.del { align-self: flex-end; background: rgba(255,59,48,0.1); color: #FF3B30; border: none; border-radius: 8px; padding: 5px 10px; cursor: pointer; font-size: 12px; }",
  "  .graph-tool-btn { background: #E5E5EA; color: #111; border: none; border-radius: 10px; padding: 7px 14px; font-size: 12px; font-weight: 600; cursor: pointer; }",
  "  .constellation-list { display: flex; gap: 6px; flex-wrap: wrap; }",
  "  .constellation-btn { display: inline-flex; align-items: center; gap: 6px; background: rgba(255,214,10,0.15); color: #7D6608; border: 1px solid rgba(255,214,10,0.5); border-radius: 10px; padding: 5px 10px; font-size: 12px; cursor: pointer; }",
  "  .constellation-btn .cx { color: #999; font-weight: 700; cursor: pointer; }",
  "  .know-item button.edit { align-self: flex-end; background: rgba(52,199,89,0.12); color: #1B8A3D; border: none; border-radius: 8px; padding: 5px 10px; cursor: pointer; font-size: 12px; }",
  "  .know-edit-area { width: 100%; border: 1px solid #E5E5EA; border-radius: 8px; padding: 8px; font-size: 13px; resize: vertical; min-height: 60px; font-family: inherit; box-sizing: border-box; }",
  "  .know-edit-actions { display: flex; gap: 6px; justify-content: flex-end; margin-top: 4px; }",
  "  #graphCanvas { width: 100%; height: 100%; display: block; cursor: grab; }",
  "  .graph-detail { display: none; margin-top: 14px; background: #F8F8FA; border: 1px solid #E5E5EA; border-radius: 18px; padding: 14px; }",
  "  .graph-detail.open { display: block; }",
  "  .graph-detail .know-meta { font-size: 11px; color: #8E8E93; margin-bottom: 8px; }",
  "",
  "  .notes-app { display: flex; height: 70vh; border: 1px solid #E5E5EA; border-radius: 18px; overflow: hidden; }",
  "  .notes-sidebar { width: 220px; min-width: 180px; background: #F8F8FA; border-right: 1px solid #E5E5EA; display: flex; flex-direction: column; }",
  "  .notes-sidebar .ns-actions { padding: 10px; display: flex; gap: 6px; flex-wrap: wrap; }",
  "  .notes-sidebar .ns-actions button { flex: 1; background: #0A84FF; color: #fff; border: none; border-radius: 8px; padding: 7px 6px; font-size: 12px; cursor: pointer; }",
  "  .notes-sidebar .ns-actions button.secondary { background: #E5E5EA; color: #111; }",
  "  .notes-sidebar input.ns-search { margin: 0 10px 8px; padding: 7px 10px; border-radius: 8px; border: 1px solid #E5E5EA; font-size: 12px; }",
  "  .notes-sidebar .ns-list { overflow-y: auto; flex: 1; }",
  "  .ns-item { padding: 8px 12px; cursor: pointer; border-bottom: 1px solid #ECECEE; font-size: 13px; }",
  "  .ns-item:hover { background: #ECECEE; }",
  "  .ns-item.active { background: #E1EBFF; }",
  "  .ns-item .ns-title { font-weight: 600; color: #000; }",
  "  .ns-item .ns-snippet { font-size: 11px; color: #8E8E93; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }",
  "  .notes-main { flex: 1; display: flex; flex-direction: column; min-width: 0; }",
  "  .notes-tabs { display: flex; border-bottom: 1px solid #E5E5EA; overflow-x: auto; background: #FCFCFD; }",
  "  .notes-tab { padding: 8px 14px; font-size: 12px; border-right: 1px solid #ECECEE; cursor: pointer; white-space: nowrap; color: #6E6E73; }",
  "  .notes-tab.active { color: #0A84FF; font-weight: 600; background: #FFFFFF; }",
  "  .notes-tab .tab-close { margin-left: 6px; color: #C7C7CC; }",
  "  .notes-panes { flex: 1; display: flex; min-height: 0; }",
  "  .note-pane { flex: 1; display: flex; flex-direction: column; padding: 14px; overflow-y: auto; border-right: 1px solid #ECECEE; min-width: 0; }",
  "  .note-pane:last-child { border-right: none; }",
  "  .note-pane input.ns-title-input { font-size: 18px; font-weight: 700; border: none; outline: none; margin-bottom: 6px; font-family: inherit; }",
  "  .note-pane input.ns-tags-input { font-size: 12px; border: 1px solid #E5E5EA; border-radius: 8px; padding: 5px 8px; margin-bottom: 8px; font-family: inherit; }",
  "  .note-pane textarea.ns-editor { flex: 1; border: 1px solid #E5E5EA; border-radius: 10px; padding: 10px; font-size: 13px; font-family: 'SF Mono', monospace; resize: none; min-height: 180px; }",
  "  .note-pane .ns-preview { flex: 1; border: 1px solid #E5E5EA; border-radius: 10px; padding: 10px; font-size: 13px; overflow-y: auto; min-height: 180px; }",
  "  .note-pane .ns-preview h1, .note-pane .ns-preview h2, .note-pane .ns-preview h3 { margin: 6px 0; }",
  "  .note-pane .ns-preview a.wikilink { color: #0A84FF; text-decoration: none; cursor: pointer; }",
  "  .note-pane .ns-toolbar { display: flex; gap: 6px; margin-bottom: 8px; flex-wrap: wrap; }",
  "  .note-pane .ns-toolbar button { font-size: 11px; padding: 5px 9px; border-radius: 7px; border: 1px solid #E5E5EA; background: #fff; cursor: pointer; }",
  "  .note-pane .ns-backlinks { margin-top: 10px; font-size: 12px; color: #6E6E73; }",
  "  .note-pane .ns-backlinks .bl-item { padding: 3px 0; color: #0A84FF; cursor: pointer; }",
  "  .ns-empty { margin: auto; color: #8E8E93; font-size: 13px; text-align: center; }",
  "  .ns-version-item { padding: 6px 8px; border-bottom: 1px solid #ECECEE; font-size: 12px; cursor: pointer; }",
  "  .ns-version-item:hover { background: #F2F2F7; }",
  "  .tpl-item { padding: 8px; border-bottom: 1px solid #ECECEE; font-size: 13px; display: flex; justify-content: space-between; align-items: center; gap: 8px; }",
  "  .tpl-item .tpl-name { font-weight: 600; flex: 1; }",
  "  .tpl-item button { background: rgba(255,59,48,0.1); color: #FF3B30; border: none; border-radius: 8px; padding: 5px 9px; cursor: pointer; font-size: 11px; }",
  "  .tpl-item button.tpl-use { background: rgba(10,132,255,0.12); color: #0A84FF; margin-right: 4px; }",
  "  .modal-box input.tpl-input, .modal-box textarea.tpl-input { width: 100%; margin-top: 6px; padding: 8px; border-radius: 8px; border: 1px solid #E5E5EA; font-family: inherit; font-size: 13px; }",
  "  .files-dropzone { border: 2px dashed #C7C7CC; border-radius: 12px; padding: 28px 16px; text-align: center; cursor: pointer; transition: background 150ms, border-color 150ms; }",
  "  .files-dropzone.dragover { background: rgba(10,132,255,0.08); border-color: #0A84FF; }",
  "  .files-dropzone-text { color: #6E6E73; font-size: 13px; }",
  "  .files-upload-status { min-height: 18px; font-size: 12px; color: #0A84FF; margin-top: 8px; text-align: center; }",
  "  .files-list { margin-top: 14px; }",
  "  .file-item { display: flex; align-items: center; gap: 10px; padding: 10px; border-bottom: 1px solid #ECECEE; }",
  "  .file-icon { font-size: 22px; }",
  "  .file-info { flex: 1; }",
  "  .file-name { font-weight: 600; font-size: 13px; }",
  "  .file-meta { font-size: 11px; color: #6E6E73; }",
  "  .file-status.done { color: #1B8A3D; }",
  "  .file-status.error { color: #FF3B30; }",
  "  .file-status.processing { color: #FF9F0A; }",
  "  .file-actions { display: flex; gap: 6px; }",
  "  .file-actions button { background: rgba(10,132,255,0.1); color: #0A84FF; border: none; border-radius: 8px; padding: 5px 9px; cursor: pointer; font-size: 11px; }",
  "  .file-actions button.del { background: rgba(255,59,48,0.1); color: #FF3B30; }",
  "",
  "  .graph-wrap { background: #FFFFFF; position: fixed; top: 0; left: 0; width: 100vw; height: 100vh; z-index: 200; display: none; overflow: hidden; }",
  "  .graph-wrap canvas { position: absolute; top: 0; left: 0; display: block; }",
  "  .graph-toolbar { position: absolute; top: 14px; left: 50%; transform: translateX(-50%); z-index: 210; display: flex; align-items: center; gap: 8px; background: rgba(255,255,255,0.92); backdrop-filter: blur(12px); border: 1px solid rgba(0,0,0,0.10); border-radius: 20px; padding: 7px 14px; box-shadow: 0 2px 12px rgba(0,0,0,0.10); white-space: nowrap; }",
  "  @media (min-width: 768px) { .bubble-row { max-width: 60%; } }",
  "  @media (min-width: 1100px) { .bubble-row { max-width: 50%; } }",
  "  .graph-close-btn { background: none; border: none; font-size: 18px; cursor: pointer; color: #1C1C1E; padding: 4px 8px; border-radius: 8px; }",
  "  .graph-close-btn:hover { background: rgba(0,0,0,0.08); }",
  "  .graph-zoom-hint { position: fixed; bottom: 18px; left: 50%; transform: translateX(-50%); z-index: 210; font-size: 11px; color: rgba(0,0,0,0.35); pointer-events: none; }",
  "  .brain-toolbar { position: relative; z-index: 220; background: transparent; }",
  "  .db-search { width: 100%; box-sizing: border-box; padding: 10px 14px; border-radius: 12px; border: 1px solid #E5E5EA; font-size: 13px; margin-bottom: 14px; font-family: inherit; }",
  "  .know-search { width: 100%; box-sizing: border-box; padding: 10px 14px; border-radius: 12px; border: 1px solid #E5E5EA; font-size: 13px; margin: 14px 0; font-family: inherit; }",
  "  .dash-wrap { padding: 24px; overflow-y: auto; width: 100%; flex: 1; min-height: 0; }",
  "  .dash-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 18px; }",
  "  .dash-card { background: var(--card); border: 1px solid var(--line); border-radius: 22px; padding: 20px; }",
  "  .dash-card.dark { background: var(--black); color: #FFFFFF; border: none; }",
  "  .dash-card .dash-label { font-size: 12px; color: #8A93A6; font-weight: 600; }",
  "  .dash-card.dark .dash-label { color: #B7BCC7; }",
  "  .dash-card .dash-value { font-size: 30px; font-weight: 800; margin-top: 6px; }",
  "  .dash-card .dash-sub { font-size: 11px; color: #8A93A6; margin-top: 4px; }",
  "  .dash-hours { display: flex; align-items: flex-end; gap: 4px; height: 90px; margin-top: 14px; }",
  "  .dash-hours .bar { flex: 1; background: var(--yellow); border-radius: 4px 4px 0 0; min-height: 3px; }",
  "  .dash-hours .bar.peak { background: var(--blue); }",
  "  .dash-products { display: flex; flex-direction: column; gap: 10px; margin-top: 14px; }",
  "  .dash-product-row { display: flex; align-items: center; gap: 10px; }",
  "  .dash-product-row .pname { flex: 1; font-size: 13px; font-weight: 600; }",
  "  .dash-product-row .pbar { flex: 2; height: 8px; border-radius: 6px; background: var(--blue-soft); overflow: hidden; }",
  "  .dash-product-row .pbar-fill { height: 100%; background: var(--blue); border-radius: 6px; }",
  "  .dash-product-row .pcount { font-size: 12px; color: #8A93A6; font-weight: 700; width: 24px; text-align: right; }",
  "  .dash-title { font-size: 22px; font-weight: 800; margin-bottom: 18px; }",
  "  .db-doc { display: flex; flex-direction: column; gap: 12px; max-width: 900px; margin: 0 auto; }",
  "  .db-section { background: #FFFFFF; border: 1px solid #E5E5EA; border-radius: 14px; overflow: hidden; }",
  "  .db-section-header { display: flex; justify-content: space-between; align-items: center; padding: 14px 18px; cursor: pointer; font-weight: 600; font-size: 15px; background: #F8F8FA; color: #1C1C1E; }",
  "  .db-section-header:hover { background: #F0F0F2; }",
  "  .db-count { font-size: 12px; color: #8E8E93; font-weight: 500; }",
  "  .db-section-body { display: none; padding: 0 18px; }",
  "  .db-section-body.open { display: block; padding: 14px 18px; }",
  "  .db-entry { padding: 10px 0; border-bottom: 1px solid #F0F0F2; }",
  "  .db-entry:last-child { border-bottom: none; }",
  "  .db-entry-meta { font-size: 10px; color: #C7C7CC; text-transform: uppercase; margin-bottom: 4px; letter-spacing: 0.4px; }",
  "  .db-entry-text { font-size: 14px; line-height: 1.6; color: #1C1C1E; font-family: Georgia, 'Times New Roman', serif; }",
  "</style>",
  "</head>",
  "<body>",
  '<div class="app-shell">',
  '<div class="app-sidebar">',
  '  <img class="logo" src="/admin/assets/logo.png" alt="Equipo Creativo" />',
  '  <div class="nav-item active" data-tab="dashboard"><span class="ic">&#128202;</span><span class="nav-label">Dashboard</span></div>',
  '  <div class="nav-item" data-tab="live"><span class="ic">&#128172;</span><span class="nav-label">Mensajes</span></div>',
  '  <div class="nav-item" data-tab="brain"><span class="ic">&#129504;</span><span class="nav-label">Cerebro</span></div>',
  "</div>",
  '<div class="app-main">',
  '<header><div class="title">ADMINISTRADOR DE CREA &#128202;</div><div class="subtitle">Equipo Creativo - Agencia de Marketing</div></header>',
  '<div class="panel active" id="dashboard">',
  '  <div class="dash-wrap">',
  '    <div class="dash-title">Dashboard</div>',
  '    <div class="dash-grid" id="dashGrid">Cargando m&eacute;tricas...</div>',
  "  </div>",
  "</div>",
  "",
  '<div class="panel" id="live">',
  '  <div class="sidebar" id="contactList"></div>',
  '  <div class="chat-area">',
  '    <div class="chat-header" id="chatHeader" style="display:none;">',
  '      <button class="user-icon-btn" id="contactInfoBtn" onclick="openContactInfo()">&#128100;</button>',
  '      <div class="chat-title" id="chatTitle"></div>',
  "    </div>",
  '    <div class="chat-messages" id="chatMessages"><div class="empty-state">Selecciona un contacto para ver la conversaci&oacute;n</div></div>',
  "  </div>",
  "</div>",
  "",
  '<div class="modal-overlay" id="contactModal">',
  '  <div class="modal-box" id="contactModalBody"></div>',
  "</div>",
  "",
  '<div class="panel brain-panel" id="brain">',
  '  <div class="brain-inner">',
  '    <div class="brain-toolbar">',
  '      <div class="view-toggle">',
  "        <button class=\"active\" data-view=\"list\" onclick=\"setBrainView('list')\">&#128203; Notas</button>",
  "        <button data-view=\"notes\" onclick=\"setBrainView('notes')\">&#128451; Base de datos</button>",
  "        <button data-view=\"graph\" onclick=\"setBrainView('graph')\">&#129504; Cerebro Central</button>",
  "        <button data-view=\"files\" onclick=\"setBrainView('files')\">&#128193; Archivos</button>",
  "      </div>",
  "    </div>",
  '    <div id="brainListView" class="brain-view active">',
  '      <div class="brain-capture">',
  '        <div id="captureTplBadge" class="capture-tpl-badge" style="display:none;"></div>',
  '        <textarea id="newKnowledge" rows="3" placeholder="Escribe algo para que Crea lo recuerde..."></textarea>',
  '        <div class="capture-actions">',
  '          <div class="capture-plus-wrap">',
  '            <button class="capture-plus" onclick="toggleCaptureMenu(event)">+</button>',
  '            <div class="capture-menu" id="captureMenu">',
  '              <div class="capture-menu-item" onclick="triggerCaptureFileAttach()">&#128206; Adjuntar archivo</div>',
  '              <div class="capture-menu-item" onclick="openCaptureTemplateMenu()">&#127991;&#65039; Seleccionar plantilla</div>',
  "            </div>",
  '            <div class="capture-menu" id="captureTemplateMenu"></div>',
  "          </div>",
  '          <button class="add" onclick="addKnowledge()">Guardar</button>',
  "        </div>",
  '        <input type="file" id="captureFileInput" accept=".pdf,.doc,.docx,.xls,.xlsx,.csv,.png,.jpg,.jpeg,.webp,.vcf" style="display:none;" />',
  "      </div>",
  '      <input class="know-search" id="knowledgeSearch" placeholder="Buscar en las notas..." oninput="renderKnowledgeList()" />',
  '      <div id="knowledgeList" class="know-list"></div>',
  "    </div>",
  '    <div id="brainGraphView" class="brain-view">',
  "    </div>",
  '    <div id="brainNotesView" class="brain-view">',
  '      <input class="db-search" id="dbSearch" placeholder="Buscar en la base de datos..." oninput="renderDatabaseSections()" />',
  '      <div class="db-doc" id="dbDoc"></div>',
  "    </div>",
  '    <div id="brainFilesView" class="brain-view">',
  '      <div class="files-dropzone" id="filesDropzone">',
  '        <div class="files-dropzone-text">Arrastra aqu&iacute; tus archivos (PDF, Word, Excel, Imagen o VCF) o haz clic para elegirlos</div>',
  '        <input type="file" id="filesInput" multiple accept=".pdf,.doc,.docx,.xls,.xlsx,.csv,.png,.jpg,.jpeg,.webp,.vcf" style="display:none;" />',
  "      </div>",
  '      <div class="files-upload-status" id="filesUploadStatus"></div>',
  '      <div class="files-list" id="filesList"></div>',
  "    </div>",
  "  </div>",
  "</div>",
  "</div>",
  "</div>",
  "",
  '<div class="modal-overlay" id="versionsModal">',
  '  <div class="modal-box" id="versionsModalBody"></div>',
  "</div>",
  "",
  '<div class="modal-overlay" id="templatesModal">',
  '  <div class="modal-box" id="templatesModalBody"></div>',
  "</div>",
  "",
  '<div class="graph-wrap" id="graphOverlay">',
  '  <div class="graph-toolbar">',
  '    <div class="constellation-list" id="constellationBtns"></div>',
  '    <button class="graph-close-btn" onclick="closeGraphOverlay()" title="Cerrar">&#10005;</button>',
  '  </div>',
  '  <canvas id="graphCanvas"></canvas>',
  '  <div class="graph-zoom-hint">Scroll para zoom &nbsp;&#183;&nbsp; Arrastra para mover</div>',
  '  <div class="graph-detail" id="graphDetail"></div>',
  "</div>",
  "",
  "<script>",
  "",
  'document.querySelectorAll(".nav-item").forEach(function (tab) {',
  "  tab.onclick = function () {",
  '    document.querySelectorAll(".nav-item").forEach(function (t) { t.classList.remove("active"); });',
  '    document.querySelectorAll(".panel").forEach(function (p) { p.classList.remove("active"); });',
  '    tab.classList.add("active");',
  '    document.getElementById(tab.dataset.tab).classList.add("active");',
  '    if (tab.dataset.tab === "dashboard") loadDashboard();',
  "  };",
  "});",
  "",
  "function loadDashboard() {",
  '  fetch("/admin/stats").then(function (r) { return r.json(); }).then(function (s) {',
  '    var grid = document.getElementById("dashGrid");',
  "    var maxHour = Math.max.apply(null, s.hourCounts.concat([1]));",
  '    var hoursHtml = s.hourCounts.map(function (c, h) {',
  '      var height = Math.max(3, Math.round((c / maxHour) * 90));',
  '      var cls = h === s.peakHour ? "bar peak" : "bar";',
  '      return \'<div class="\' + cls + \'" style="height:\' + height + \'px" title="\' + h + \':00 - \' + c + \'"></div>\';',
  '    }).join("");',
  '    var productsHtml = s.topProducts.length ? s.topProducts.map(function (p) {',
  "      var maxCount = s.topProducts[0].count || 1;",
  '      var pct = Math.round((p.count / maxCount) * 100);',
  '      return \'<div class="dash-product-row"><div class="pname">\' + escapeHtml(p.name) + \'</div><div class="pbar"><div class="pbar-fill" style="width:\' + pct + \'%"></div></div><div class="pcount">\' + p.count + "</div></div>";',
  '    }).join("") : \'<div class="dash-sub">A&uacute;n no hay suficientes datos.</div>\';',
  '    grid.innerHTML =',
  '      \'<div class="dash-card dark"><div class="dash-label">Total de mensajes</div><div class="dash-value">\' + s.totalMessages + \'</div><div class="dash-sub">\' + s.uniqueContacts + " contactos &uacute;nicos</div></div>" +',
  '      \'<div class="dash-card"><div class="dash-label">Han agendado</div><div class="dash-value">\' + s.bookedRatio + \'%</div><div class="dash-sub">\' + s.bookedContacts + " de " + s.uniqueContacts + " contactos</div></div>" +',
  '      \'<div class="dash-card"><div class="dash-label">Citas pr&oacute;ximas</div><div class="dash-value">\' + s.upcomingAppointments + "</div></div>" +',
  '      \'<div class="dash-card" style="grid-column: span 2;"><div class="dash-label">Horario con m&aacute;s mensajes</div><div class="dash-value">\' + s.peakHour + ":00 hrs</div><div class=\\"dash-hours\\">" + hoursHtml + "</div></div>" +',
  '      \'<div class="dash-card"><div class="dash-label">Productos m&aacute;s preguntados</div><div class="dash-products">\' + productsHtml + "</div></div>";',
  "  }).catch(function () {",
  '    document.getElementById("dashGrid").innerHTML = \'<div class="dash-sub">No se pudieron cargar las m&eacute;tricas.</div>\';',
  "  });",
  "}",
  "loadDashboard();",
  "",
  "var allMessages = [];",
  "var selectedPhone = null;",
  "",
  "function contactLabel(phone) {",
  '  if (phone === ADMIN_PHONE) return "Admin (tú)";',
  "  return phone;",
  "}",
  "",
  "function escapeHtml(text) {",
  '  return text.replace(/</g, "&lt;");',
  "}",
  "",
  "function formatTime(iso) {",
  '  return new Date(iso + "Z").toLocaleTimeString("es-MX", { hour: "2-digit", minute: "2-digit" });',
  "}",
  "",
  "function groupByPhone(messages) {",
  "  var map = {};",
  "  messages.forEach(function (m) {",
  "    if (!map[m.phone]) map[m.phone] = [];",
  "    map[m.phone].push(m);",
  "  });",
  "  return map;",
  "}",
  "",
  "function renderContactList() {",
  "  var grouped = groupByPhone(allMessages);",
  "  var phones = Object.keys(grouped);",
  "  phones.sort(function (a, b) {",
  "    var lastA = grouped[a][grouped[a].length - 1];",
  "    var lastB = grouped[b][grouped[b].length - 1];",
  "    return new Date(lastB.created_at) - new Date(lastA.created_at);",
  "  });",
  '  var container = document.getElementById("contactList");',
  '  container.innerHTML = "";',
  "  phones.forEach(function (phone) {",
  "    var msgs = grouped[phone];",
  "    var last = msgs[msgs.length - 1];",
  '    var div = document.createElement("div");',
  '    div.className = "contact" + (phone === selectedPhone ? " active" : "");',
  "    div.onclick = function () { selectContact(phone); };",
  '    div.innerHTML = "<div class=\\"time\\">" + formatTime(last.created_at) + "</div>" +',
  '      "<div class=\\"name\\">" + escapeHtml(contactLabel(phone)) + "</div>" +',
  '      "<div class=\\"preview\\">" + escapeHtml(last.text) + "</div>";',
  "    container.appendChild(div);",
  "  });",
  "}",
  "",
  "function renderBubble(row) {",
  '  var direction = row.direction === "out" ? "sent" : "received";',
  '  var rowDiv = document.createElement("div");',
  '  rowDiv.className = "bubble-row " + direction;',
  "",
  '  var bubble = document.createElement("div");',
  '  bubble.className = "bubble " + direction;',
  "  bubble.textContent = row.text;",
  "  rowDiv.appendChild(bubble);",
  "",
  '  if (direction === "sent") {',
  '    var copyBtn = document.createElement("button");',
  '    copyBtn.className = "copy-btn";',
  '    copyBtn.title = "Copiar mensaje";',
  '    copyBtn.textContent = "📋";',
  "    copyBtn.onclick = function (e) {",
  "      e.stopPropagation();",
  "      navigator.clipboard.writeText(row.text).then(function () {",
  '        copyBtn.textContent = "✓";',
  '        setTimeout(function () { copyBtn.textContent = "📋"; }, 1200);',
  "      });",
  "    };",
  "    rowDiv.appendChild(copyBtn);",
  "  }",
  "",
  '  var time = document.createElement("div");',
  '  time.className = "timestamp";',
  "  time.textContent = formatTime(row.created_at);",
  "  rowDiv.appendChild(time);",
  "",
  "  return rowDiv;",
  "}",
  "",
  "function selectContact(phone) {",
  "  selectedPhone = phone;",
  "  renderContactList();",
  "  renderChat();",
  '  document.getElementById("chatHeader").style.display = "flex";',
  '  document.getElementById("chatTitle").textContent = contactLabel(phone);',
  "}",
  "",
  "async function openContactInfo() {",
  "  if (!selectedPhone) return;",
  '  var res = await fetch("/admin/contact/" + selectedPhone);',
  "  var info = await res.json();",
  '  var body = document.getElementById("contactModalBody");',
  '  var html = "<h3>" + escapeHtml(contactLabel(selectedPhone)) + "</h3>";',
  '  html += "<div class=\\"field\\"><div class=\\"label\\">Número</div><div class=\\"value\\">" + escapeHtml(selectedPhone) + "</div></div>";',
  '  html += "<div class=\\"field\\"><div class=\\"label\\">Nombre</div><div class=\\"value\\">" + escapeHtml(info.name || "Sin nombre registrado") + "</div></div>";',
  '  html += "<div class=\\"field\\"><div class=\\"label\\">Citas</div>";',
  "  if (info.appointments.length === 0) {",
  '    html += "<div class=\\"value\\">Sin citas registradas</div>";',
  "  } else {",
  "    info.appointments.forEach(function (a) {",
  '      html += "<div class=\\"appt-item\\">" + escapeHtml(a.service || "Servicio") + " — " + escapeHtml(a.start_iso) + " (" + escapeHtml(a.status) + ")</div>";',
  "    });",
  "  }",
  '  html += "</div>";',
  '  html += "<div class=\\"field\\"><div class=\\"label\\">Notas del segundo cerebro</div>";',
  "  if (info.notes.length === 0) {",
  '    html += "<div class=\\"value\\">Sin notas</div>";',
  "  } else {",
  "    info.notes.forEach(function (n) {",
  '      html += "<div class=\\"note-item\\">" + escapeHtml(n) + "</div>";',
  "    });",
  "  }",
  '  html += "</div>";',
  '  html += "<button class=\\"close-btn\\" onclick=\\"closeContactInfo()\\">Cerrar</button>";',
  "  body.innerHTML = html;",
  '  document.getElementById("contactModal").classList.add("open");',
  "}",
  "",
  "function closeContactInfo() {",
  '  document.getElementById("contactModal").classList.remove("open");',
  "}",
  "",
  "function renderChat() {",
  '  var container = document.getElementById("chatMessages");',
  '  container.innerHTML = "";',
  "  if (!selectedPhone) {",
  '    container.innerHTML = "<div class=\\"empty-state\\">Selecciona un contacto para ver la conversación</div>";',
  "    return;",
  "  }",
  "  var grouped = groupByPhone(allMessages);",
  "  var msgs = grouped[selectedPhone] || [];",
  "  msgs.forEach(function (row) { container.appendChild(renderBubble(row)); });",
  "  container.scrollTop = container.scrollHeight;",
  "}",
  "",
  "async function loadMessages() {",
  '  var res = await fetch("/admin/messages");',
  "  allMessages = await res.json();",
  "  renderContactList();",
  "  renderChat();",
  "}",
  "",
  'var evtSource = new EventSource("/admin/stream");',
  "evtSource.onmessage = function (e) {",
  "  var row = JSON.parse(e.data);",
  "  allMessages.push(row);",
  "  renderContactList();",
  "  if (row.phone === selectedPhone) {",
  '    var container = document.getElementById("chatMessages");',
  "    container.appendChild(renderBubble(row));",
  "    container.scrollTop = container.scrollHeight;",
  "  }",
  "};",
  "",
"var allKnowledge = [];",
  "var hubNotes = [];",
  "var autoClusters = [];",
  "var brainView = \"list\";",
  "",
  "function setBrainView(view) {",
  "  brainView = view;",
  '  document.querySelectorAll(".view-toggle button").forEach(function (b) {',
  '    b.classList.toggle("active", b.dataset.view === view);',
  "  });",
  '  document.getElementById("brainListView").classList.toggle("active", view === "list");',
  '  document.getElementById("brainGraphView").classList.toggle("active", view === "graph");',
  '  document.getElementById("brainNotesView").classList.toggle("active", view === "notes");',
  '  document.getElementById("brainFilesView").classList.toggle("active", view === "files");',
  "  var overlay = document.getElementById('graphOverlay');",
  "  if (view === \"graph\") {",
  "    overlay.style.display = 'flex';",
  "    renderGraph();",
  "  } else {",
  "    overlay.style.display = 'none';",
  "    if (graphAnimId) { cancelAnimationFrame(graphAnimId); graphAnimId = null; }",
  "  }",
  "  if (view === \"notes\") {",
  "    loadDatabaseView();",
  "  }",
  "  if (view === \"files\") {",
  "    loadFiles();",
  "  }",
  "}",
  "",
  "var dbSections = [];",
  "async function loadDatabaseView() {",
  '  var res = await fetch("/admin/knowledge");',
  "  var entries = await res.json();",
  '  var cres = await fetch("/admin/auto-clusters");',
  "  var clusters = await cres.json();",
  "  var used = {};",
  "  var sections = clusters.map(function (c) {",
  "    var items = entries.filter(function (e) { return c.noteIds.indexOf(e.id) !== -1; });",
  "    items.forEach(function (e) { used[e.id] = true; });",
  "    return { name: c.name, items: items };",
  "  }).filter(function (s) { return s.items.length; });",
  "  var rest = entries.filter(function (e) { return !used[e.id]; });",
  '  if (rest.length) sections.push({ name: "General", items: rest });',
  "  dbSections = sections;",
  "  renderDatabaseSections();",
  "}",
  "",
  "function renderDatabaseSections() {",
  '  var wrap = document.getElementById("dbDoc");',
  '  var q = (document.getElementById("dbSearch").value || "").toLowerCase();',
  "  var sections = dbSections.map(function (s) {",
  "    var items = !q ? s.items : s.items.filter(function (e) {",
  '      return ((e.content || "") + " " + (e.title || "")).toLowerCase().indexOf(q) !== -1;',
  "    });",
  "    return { name: s.name, items: items };",
  "  }).filter(function (s) { return s.items.length; });",
  "  if (!sections.length) {",
  '    wrap.innerHTML = \'<div class="ns-empty">A\\u00fan no hay informaci\\u00f3n guardada.</div>\';',
  "    return;",
  "  }",
  "  wrap.innerHTML = sections.map(function (s, i) {",
  "    var body = s.items.map(function (e) {",
  '      var tag = e.source === "auto" ? "Autom\\u00e1tico" : "Manual";',
  '      return \'<div class="db-entry"><div class="db-entry-meta">\' + tag + \'</div><div class="db-entry-text">\' + escapeHtml(e.content || "").replace(/\\n/g, "<br>") + "</div></div>";',
  '    }).join("");',
  '    return \'<div class="db-section">\' +',
  '      \'<div class="db-section-header" onclick="toggleDbSection(\' + i + \')">\' +',
  '        "<span>" + escapeHtml(s.name) + "</span>" +',
  '        \'<span class="db-count">\' + s.items.length + "</span>" +',
  "      \"</div>\" +",
  '      \'<div class="db-section-body" id="dbSection\' + i + \'">\' + body + "</div>" +',
  "    \"</div>\";",
  '  }).join("");',
  "}",
  "",
  "function toggleDbSection(i) {",
  '  var el = document.getElementById("dbSection" + i);',
  '  el.classList.toggle("open");',
  "}",
  "",
  "function closeGraphOverlay() {",
  "  setBrainView('list');",
  "}",
  "",
  "function formatDate(iso) {",
  '  return new Date(iso + "Z").toLocaleDateString("es-MX", { day: "2-digit", month: "short" });',
  "}",
  "",
  "async function loadKnowledge() {",
  '  var res = await fetch("/admin/knowledge");',
  "  allKnowledge = await res.json();",
  "  renderKnowledgeList();",
  "  if (brainView === \"graph\") renderGraph();",
  "}",
  "",
  "function renderKnowledgeList() {",
  '  var q = (document.getElementById("knowledgeSearch").value || "").toLowerCase();',
  "  var rows = !q ? allKnowledge : allKnowledge.filter(function (row) {",
  '    return ((row.content || "") + " " + (row.title || "")).toLowerCase().indexOf(q) !== -1;',
  "  });",
  '  var list = document.getElementById("knowledgeList");',
  '  list.innerHTML = "";',
  "  rows.forEach(function (row) {",
  '    var div = document.createElement("div");',
  '    div.className = "know-item";',
  "    var safeContent = escapeHtml(row.content);",
  '    var tagClass = row.source === "auto" ? "source-tag auto" : "source-tag";',
  '    var tagLabel = row.source === "auto" ? "auto" : "manual";',
  '    var titleHtml = row.title ? "<div style=\\"font-size:13px;font-weight:700;color:#1C1C1E;margin-bottom:4px;\\">" + escapeHtml(row.title) + "</div>" : "";',
  '    div.innerHTML = titleHtml + "<div class=\\"know-content\\" id=\\"kc-" + row.id + "\\">" + safeContent + "</div>" +',
  '      "<div class=\\"know-meta\\"><span class=\\"" + tagClass + "\\">" + tagLabel + "</span><span>" + formatDate(row.created_at) + "</span></div>" +',
  '      "<div style=\\"display:flex;gap:6px;justify-content:flex-end;\\"><button class=\\"edit\\" onclick=\\"editKnowledge(" + row.id + ", this)\\">Editar</button><button class=\\"del\\" onclick=\\"deleteKnowledge(" + row.id + ")\\">Borrar</button></div>";',
  "    list.appendChild(div);",
  "  });",
  "}",
  "",
  "var activeCaptureTemplate = null;",
  "",
  "function toggleCaptureMenu(e) {",
  "  e.stopPropagation();",
  '  document.getElementById("captureTemplateMenu").classList.remove("open");',
  '  document.getElementById("captureMenu").classList.toggle("open");',
  "}",
  "",
  'document.addEventListener("click", function (e) {',
  "  if (!e.target.closest || !e.target.closest(\".capture-plus-wrap\")) {",
  '    var m1 = document.getElementById("captureMenu");',
  '    var m2 = document.getElementById("captureTemplateMenu");',
  "    if (m1) m1.classList.remove(\"open\");",
  "    if (m2) m2.classList.remove(\"open\");",
  "  }",
  "});",
  "",
  "function triggerCaptureFileAttach() {",
  '  document.getElementById("captureMenu").classList.remove("open");',
  '  document.getElementById("captureFileInput").click();',
  "}",
  "",
  'document.getElementById("captureFileInput").onchange = async function () {',
  "  var input = this;",
  "  if (!input.files.length) return;",
  "  var formData = new FormData();",
  '  formData.append("file", input.files[0]);',
  '  var textarea = document.getElementById("newKnowledge");',
  '  textarea.value = (textarea.value ? textarea.value + "\\n" : "") + "📎 Adjuntando " + input.files[0].name + "…";',
  "  try {",
  '    var res = await fetch("/admin/files/upload", { method: "POST", body: formData });',
  "    var file = await res.json();",
  "    if (res.ok) {",
  '      textarea.value = textarea.value.replace("📎 Adjuntando " + file.original_name + "…", "📎 Archivo adjunto: " + file.original_name + " (ver en pestaña Archivos)");',
  "    } else {",
  '      textarea.value = textarea.value.replace("📎 Adjuntando " + input.files[0].name + "…", "");',
  '      alert(file.error || "No se pudo adjuntar el archivo");',
  "    }",
  "  } catch (err) {",
  '    console.error("Error al adjuntar archivo:", err);',
  '    textarea.value = textarea.value.replace("📎 Adjuntando " + input.files[0].name + "…", "");',
  '    alert("No se pudo adjuntar el archivo: " + (err.message || err));',
  "  }",
  '  input.value = "";',
  "};",
  "",
  "async function openCaptureTemplateMenu() {",
  '  document.getElementById("captureMenu").classList.remove("open");',
  '  var res = await fetch("/admin/templates");',
  "  var templates = await res.json();",
  '  var menu = document.getElementById("captureTemplateMenu");',
  '  var html = "";',
  "  if (templates.length === 0) {",
  '    html = "<div class=\\"capture-menu-item\\">Sin plantillas — créalas en Notas</div>";',
  "  } else {",
  "    templates.forEach(function (t) {",
  '      html += "<div class=\\"capture-menu-item\\" onclick=\\"selectCaptureTemplate(" + t.id + ", \'" + escapeHtml(t.name).replace(/\'/g, "&#39;") + "\')\\">" + escapeHtml(t.name) + "</div>";',
  "    });",
  "  }",
  "  menu.innerHTML = html;",
  '  menu.classList.add("open");',
  "}",
  "",
  "function selectCaptureTemplate(id, name) {",
  "  activeCaptureTemplate = { id: id, name: name };",
  '  document.getElementById("captureTemplateMenu").classList.remove("open");',
  '  var badge = document.getElementById("captureTplBadge");',
  '  badge.style.display = "inline-flex";',
  '  badge.innerHTML = "🏷️ Plantilla: " + escapeHtml(name) + " <span class=\\"x\\" onclick=\\"clearCaptureTemplate()\\">×</span>";',
  "}",
  "",
  "function clearCaptureTemplate() {",
  "  activeCaptureTemplate = null;",
  '  var badge = document.getElementById("captureTplBadge");',
  '  badge.style.display = "none";',
  '  badge.innerHTML = "";',
  "}",
  "",
  "async function ensureTemplateHubNote(name) {",
  '  var res = await fetch("/admin/notes");',
  "  var notes = await res.json();",
  "  var hub = notes.find(function (n) {",
  '    return (n.tags || []).indexOf("plantilla-hub") !== -1 && (n.title || "").toLowerCase() === name.toLowerCase();',
  "  });",
  "  if (hub) return hub;",
  '  var createRes = await fetch("/admin/notes", {',
  '    method: "POST",',
  '    headers: { "Content-Type": "application/json" },',
  '    body: JSON.stringify({ title: name, content: "", tags: [name, "plantilla-hub"] }),',
  "  });",
  "  return createRes.json();",
  "}",
  "",
"async function addKnowledge() {",
  '  var textarea = document.getElementById("newKnowledge");',
  "  var content = textarea.value.trim();",
  "  if (!content) return;",
  '  var saveBtn = document.querySelector(".brain-capture button.add");',
  "  if (saveBtn) { saveBtn.disabled = true; }",
  "  try {",
  "    if (activeCaptureTemplate) {",
  '      var hubRes = await fetch("/admin/hub-save", {',
  '        method: "POST",',
  '        headers: { "Content-Type": "application/json" },',
  '        body: JSON.stringify({ templateName: activeCaptureTemplate.name, entryContent: content }),',
  "      });",
  '      if (!hubRes.ok) { var hubErr = await hubRes.json().catch(function(){return {};}); throw new Error(hubErr.error || "Error al guardar con plantilla (" + hubRes.status + ")"); }',
  "    } else {",
  '      var res2 = await fetch("/admin/knowledge", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ content: content }) });',
  '      if (!res2.ok) throw new Error("No se pudo guardar (" + res2.status + ")");',
  "    }",
  '    textarea.value = "";',
  "    loadKnowledge();",
  "  } catch (err) {",
  '    console.error("Error al guardar:", err);',
  '    alert("No se pudo guardar: " + (err.message || err));',
  "  } finally {",
  "    if (saveBtn) { saveBtn.disabled = false; }",
  "  }",
  "}",
  "",
  "function editKnowledge(id, btnEl) {",
  '  var card = btnEl.closest(".know-item") || btnEl.closest(".graph-detail");',
  '  var contentEl = card ? card.querySelector("#kc-" + id + ", .know-content") : null;',
  "  if (!contentEl) return;",
  "  var current = contentEl.textContent;",
  '  var ta = document.createElement("textarea");',
  '  ta.className = "know-edit-area";',
  "  ta.value = current;",
  "  contentEl.replaceWith(ta);",
  "  ta.focus();",
  '  var actionsDiv = document.createElement("div");',
  '  actionsDiv.className = "know-edit-actions";',
  '  actionsDiv.innerHTML = "<button class=\\\"add\\\" onclick=\\\"saveKnowledge(" + id + ", this)\\\">Guardar</button>" +',
  '    "<button class=\\\"del\\\" onclick=\\\"cancelEditKnowledge(" + id + ", this)\\\">Cancelar</button>";',
  "  ta.after(actionsDiv);",
  "  var editBtn = card ? card.querySelector('.edit') : null;",
  "  if (editBtn) editBtn.style.display = 'none';",
  "}",
  "",
  "async function saveKnowledge(id, btnEl) {",
  '  var actionsDiv = btnEl.closest(".know-edit-actions");',
  "  var ta = actionsDiv ? actionsDiv.previousElementSibling : null;",
  "  if (!ta) return;",
  "  var newContent = ta.value.trim();",
  "  if (!newContent) return;",
  '  var res = await fetch("/admin/knowledge/" + id, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ content: newContent }) });',
  "  if (res.ok) { loadKnowledge(); if (brainView === 'graph') renderGraph(); }",
  '  else { alert("No se pudo guardar"); }',
  "}",
  "",
  "function cancelEditKnowledge(id, btnEl) {",
  '  var actionsDiv = btnEl.closest(".know-edit-actions");',
  "  if (actionsDiv) actionsDiv.remove();",
  "  loadKnowledge();",
  "}",
  "",
"async function deleteKnowledge(id) {",
  '  await fetch("/admin/knowledge/" + id, { method: "DELETE" });',
  '  document.getElementById("graphDetail").classList.remove("open");',
  "  loadKnowledge();",
  "}",
  "",
  "var graphNodes = [];",
  "var hoveredNode = null;",
  "var graphAnimId = null;",
  "var graphDragNode = null;",
  "var graphDragMoved = false;",
  "var graphW = 0;",
  "var graphH = 0;",
  "var constellations = {};",
  "var graphZoom = 1;",
  "var graphPanX = 0;",
  "var graphPanY = 0;",
  "var graphIsPanning = false;",
  "var graphPanStartX = 0;",
  "var graphPanStartY = 0;",
  "var graphZoomTarget = 1;",
  "var graphPanXTarget = 0;",
  "var graphPanYTarget = 0;",
  "var graphResetting = false;",
  "var graphScale = 1;",
  "",
  "function loadConstellations() {",
  "  try { constellations = JSON.parse(localStorage.getItem('graphConstellations') || '{}'); } catch(e) { constellations = {}; }",
  "  renderConstellationBtns();",
  "}",
  "",
  "function saveConstellation() {",
  "  var name = prompt('Nombre para esta vista (constelacion):');",
  "  if (!name || !name.trim()) return;",
  "  var positions = {};",
  "  graphNodes.forEach(function(n) { positions[n.id] = { x: n.x, y: n.y }; });",
  "  constellations[name.trim()] = positions;",
  "  try { localStorage.setItem('graphConstellations', JSON.stringify(constellations)); } catch(e) {}",
  "  renderConstellationBtns();",
  "}",
  "",
  "function deleteConstellation(name) {",
  "  delete constellations[name];",
  "  try { localStorage.setItem('graphConstellations', JSON.stringify(constellations)); } catch(e) {}",
  "  renderConstellationBtns();",
  "}",
  "",
  "function applyConstellation(name) {",
  "  var positions = constellations[name];",
  "  if (!positions) return;",
  "  graphNodes.forEach(function(n) {",
  "    if (positions[n.id]) { n.x = positions[n.id].x; n.y = positions[n.id].y; n.vx = 0; n.vy = 0; }",
  "  });",
  "}",
  "",
  "function renderConstellationBtns() {",
  '  var el = document.getElementById("constellationBtns");',
  "  if (!el) return;",
  '  el.innerHTML = "";',
  "  Object.keys(constellations).forEach(function(name) {",
  '    var btn = document.createElement("button");',
  '    btn.className = "constellation-btn";',
  '    btn.innerHTML = "&#11088; " + escapeHtml(name) + " <span class=\\\"cx\\\" onclick=\\\"deleteConstellation(" + JSON.stringify(name) + ");event.stopPropagation()\\\">x</span>";',
  "    btn.onclick = function() { applyConstellation(name); };",
  "    el.appendChild(btn);",
  "  });",
  "}",
  "",
  "function stripEmoji(s) {",
  "  return (s||''). replace(/[^\\w\\u00c0-\\u024f\\s]/g,'').trim().toLowerCase().replace(/\\s+/g,'');",
  "}",
  "",
"function buildGraphNodes() {",
  "  var stop = ['que','para','con','los','las','una','uno','del','por','sus','esta','esto','como','tiene','pero','hace','muy','mas','son','fue','han','van','sin','hay','ser','este','todo','cada','cuando','donde'];",
  "  function kw(text) {",
  "    return ((text||'').toLowerCase().match(/[a-zà-ÿ]{4,}/g)||[]).filter(function(w){return stop.indexOf(w)===-1;});",
  "  }",
  "",
  "  var hub = { id:0, label:'Crea', source:'hub', words:[], isHub:true, isTemplate:false, isCluster:false, degree:0 };",
  "",
  "  var templates = hubNotes.map(function(hn) {",
  "    return { id:'tmpl_'+hn.id, dbId:hn.id, label:hn.title||hn.content.slice(0,16),",
  "      source:'template', words:kw(hn.content+' '+hn.title), isHub:false, isTemplate:true, isCluster:false,",
  "      templateSlug:stripEmoji(hn.title), degree:0 };",
  "  });",
  "",
  "  var clusterNodes = (autoClusters||[]).map(function(c) {",
  "    var alreadyTemplate = templates.some(function(t){ return t.templateSlug===c.keyword; });",
  "    if (alreadyTemplate) return null;",
  "    return { id:'cl_'+c.keyword, label:c.name, keyword:c.keyword, noteIds:c.noteIds,",
  "      source:'cluster', words:[c.keyword], isHub:false, isTemplate:false, isCluster:true, degree:0 };",
  "  }).filter(Boolean);",
  "",
  "  var entries = allKnowledge.map(function(row) {",
  "    return { id:row.id, label:row.title||(row.content.length>22?row.content.slice(0,22)+'...':row.content),",
  "      content:row.content, source:row.source, words:kw(row.content+' '+(row.title||'')),",
  "      isHub:false, isTemplate:false, isCluster:false, degree:0 };",
  "  });",
  "",
  "  // Count degrees",
  "  var midNodes = templates.concat(clusterNodes);",
  "  entries.forEach(function(e) {",
  "    var parent = entryParent(e, midNodes);",
  "    if (parent) { e.degree++; parent.degree++; }",
  "    else hub.degree++;",
  "  });",
  "  midNodes.forEach(function(m) { hub.degree++; m.degree++; });",
  "",
  "  return [hub].concat(midNodes).concat(entries);",
  "}",
  "",
  "function entryParent(entry, midNodes) {",
  "  var c = (entry.content||'').toLowerCase();",
  "  // 1. Template match by #slug",
  "  var byTag = midNodes.find(function(m) {",
  "    if (!m.isTemplate) return false;",
  "    var slug = m.templateSlug;",
  "    return slug && c.indexOf('#'+slug) !== -1;",
  "  });",
  "  if (byTag) return byTag;",
  "  // 2. Cluster match by keyword presence",
  "  var best = null, bestScore = 0;",
  "  midNodes.forEach(function(m) {",
  "    if (!m.isCluster) return;",
  "    var score = entry.words.filter(function(w){ return m.words.indexOf(w)!==-1; }).length;",
  "    if (score > bestScore) { bestScore = score; best = m; }",
  "  });",
  "  return bestScore > 0 ? best : null;",
  "}",
  "",
  "function stepPhysics(nodes) {",
  "  var hub = nodes[0];",
  "  hub.x = graphW/2; hub.y = graphH/2; hub.vx = 0; hub.vy = 0;",
  "  nodes.forEach(function(n){ n.fx = 0; n.fy = 0; });",
  "  var midNodes = nodes.filter(function(n){ return n.isTemplate||n.isCluster; });",
  "  var entryNodes = nodes.filter(function(n){ return !n.isHub&&!n.isTemplate&&!n.isCluster; });",
  "",
  "  // Repulsion between all non-hub nodes",
  "  for (var i=1;i<nodes.length;i++) {",
  "    for (var j=i+1;j<nodes.length;j++) {",
  "      var a=nodes[i],b=nodes[j];",
  "      var dx=a.x-b.x,dy=a.y-b.y,dist=Math.max(Math.hypot(dx,dy),1);",
  "      var minD=a.r+b.r+32;",
  "      var force=3200/(dist*dist);",
  "      if(dist<minD) force+=(minD-dist)*0.6;",
  "      var fx=(dx/dist)*force,fy=(dy/dist)*force;",
  "      a.fx+=fx;a.fy+=fy;b.fx-=fx;b.fy-=fy;",
  "    }",
  "  }",
  "",
  "  // Mid-nodes spring toward hub",
  "  midNodes.forEach(function(m) {",
  "    var dx=hub.x-m.x,dy=hub.y-m.y,d=Math.max(Math.hypot(dx,dy),1);",
  "    var targetDist=Math.min(graphW,graphH)*0.28*graphScale;",
  "    var sf=(d-targetDist)*0.018;",
  "    m.fx+=(dx/d)*sf;m.fy+=(dy/d)*sf;",
  "  });",
  "",
  "  // Entries spring toward their parent (mid-node or hub)",
  "  entryNodes.forEach(function(e) {",
  "    var parent=entryParent(e,midNodes)||hub;",
  "    var dx=parent.x-e.x,dy=parent.y-e.y,d=Math.max(Math.hypot(dx,dy),1);",
  "    var targetDist=Math.min(graphW,graphH)*0.22*graphScale;",
  "    var sf=(d-targetDist)*0.010;",
  "    e.fx+=(dx/d)*sf;e.fy+=(dy/d)*sf;",
  "  });",
  "",
  "  for (var k=1;k<nodes.length;k++) {",
  "    var n=nodes[k];",
  "    if(n===graphDragNode) continue;",
  "    n.vx=(n.vx+n.fx)*0.62;",
  "    n.vy=(n.vy+n.fy)*0.62;",
  "    n.x+=n.vx;n.y+=n.vy;",
  "  }",
  "}",
  "",
  "function drawGraph(ctx, nodes, time) {",
  "  ctx.fillStyle='#FFFFFF';",
  "  ctx.fillRect(0,0,graphW,graphH);",
  "  var hub=nodes[0];",
  "  var midNodes=nodes.filter(function(n){return n.isTemplate||n.isCluster;});",
  "  var entryNodes=nodes.filter(function(n){return !n.isHub&&!n.isTemplate&&!n.isCluster;});",
  "  var showLeaves=true;",
  "",
  "  var hovSet={};",
  "  if(hoveredNode) {",
  "    hovSet[hoveredNode.id]=true;",
  "    if(hoveredNode.isHub) { midNodes.forEach(function(m){hovSet[m.id]=true;}); }",
  "    else if(hoveredNode.isTemplate||hoveredNode.isCluster) {",
  "      hovSet[hub.id]=true;",
  "      entryNodes.forEach(function(e){ if(entryParent(e,midNodes)===hoveredNode) hovSet[e.id]=true; });",
  "    } else {",
  "      var par=entryParent(hoveredNode,midNodes);",
  "      if(par) hovSet[par.id]=true; else hovSet[hub.id]=true;",
  "    }",
  "  }",
  "",
  "  ctx.save();",
  "  ctx.translate(graphPanX, graphPanY);",
  "  ctx.scale(graphZoom, graphZoom);",
  "",
  "  ctx.lineWidth=0.8/graphZoom;",
  "",
  "  midNodes.forEach(function(m) {",
  "    var lit=!hoveredNode||hovSet[m.id];",
  "    ctx.strokeStyle=m.isTemplate?",
  "      (lit?'rgba(180,130,0,0.55)':'rgba(180,130,0,0.08)'):",
  "      (lit?'rgba(0,150,130,0.45)':'rgba(0,150,130,0.08)');",
  "    ctx.beginPath();ctx.moveTo(hub.x,hub.y);ctx.lineTo(m.x,m.y);ctx.stroke();",
  "  });",
  "",
  "  if(showLeaves) {",
  "    entryNodes.forEach(function(e) {",
  "      var par=entryParent(e,midNodes);",
  "      var anchor=par||hub;",
  "      var lit=!hoveredNode||hovSet[e.id]||hovSet[anchor.id];",
  "      if(par&&par.isTemplate) ctx.strokeStyle=lit?'rgba(180,130,0,0.25)':'rgba(180,130,0,0.04)';",
  "      else if(par&&par.isCluster) ctx.strokeStyle=lit?'rgba(0,150,130,0.22)':'rgba(0,150,130,0.04)';",
  "      else ctx.strokeStyle=lit?'rgba(80,100,200,0.18)':'rgba(80,100,200,0.03)';",
  "      ctx.beginPath();ctx.moveTo(anchor.x,anchor.y);ctx.lineTo(e.x,e.y);ctx.stroke();",
  "    });",
  "    if(entryNodes.length<=120) {",
  "      for(var i=0;i<entryNodes.length;i++) {",
  "        for(var j=i+1;j<entryNodes.length;j++) {",
  "          var a=entryNodes[i],b=entryNodes[j];",
  "          var sc=a.words.filter(function(w){return b.words.indexOf(w)!==-1;}).length;",
  "          if(!sc) continue;",
  "          var lit2=!hoveredNode||(hovSet[a.id]&&hovSet[b.id]);",
  "          ctx.strokeStyle=lit2?'rgba(80,100,200,0.35)':'rgba(80,100,200,0.03)';",
  "          ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();",
  "        }",
  "      }",
  "    }",
  "  }",
  "",
  "  var drawList=showLeaves?nodes:[hub].concat(midNodes);",
  "  drawList.forEach(function(n) {",
  "    var breathe=Math.sin(time*0.0012+n.phase)*(n.isHub?1.8:n.isTemplate||n.isCluster?0.9:0.5);",
  "    var r=n.r+breathe;",
  "    var isHov=n===hoveredNode;",
  "    var isDim=hoveredNode&&!hovSet[n.id]&&!isHov;",
  "    ctx.save();",
  "    ctx.globalAlpha=isDim?0.12:1;",
  "    if(isHov){ctx.shadowBlur=18/graphZoom;ctx.shadowColor=n.isHub?'#333':n.isTemplate?'#B8860B':n.isCluster?'#00796B':'#4050C8';}",
  "    ctx.beginPath();ctx.arc(n.x,n.y,r,0,Math.PI*2);",
  "    ctx.fillStyle=n.isHub?'#1C1C1E':n.isTemplate?'#F5C400':n.isCluster?'#00897B':(n.source==='auto'?'#8E44AD':'#4050C8');",
  "    ctx.fill();",
  "    ctx.restore();",
  "    ctx.save();",
  "    ctx.globalAlpha=isDim?0.08:0.95;",
  "    ctx.font=(n.isHub?'bold 13px':n.isTemplate||n.isCluster?'bold 11px':'10px')+' -apple-system,sans-serif';",
  "    ctx.fillStyle=n.isHub?'#FFFFFF':'#1C1C1E';",
  "    ctx.fillText(n.label,n.x+r+5,n.y+4);",
  "    ctx.restore();",
  "  });",
  "",
  "  ctx.restore();",
  "}",
  "",
  "function renderGraph() {",
  '  var canvas = document.getElementById("graphCanvas");',
  '  var wrap = document.getElementById("graphOverlay");',
  "  var dpr=window.devicePixelRatio||1;",
  "  graphW=wrap.clientWidth;graphH=wrap.clientHeight;",
  "  if(!graphW||!graphH){ setTimeout(renderGraph,120); return; }",
  "  graphResetting=false;",
  "  canvas.width=graphW*dpr;canvas.height=graphH*dpr;",
  "  canvas.style.width=graphW+'px';canvas.style.height=graphH+'px';",
  '  var ctx=canvas.getContext("2d");',
  "  ctx.scale(dpr,dpr);",
  "  if(graphAnimId) cancelAnimationFrame(graphAnimId);",
  "  Promise.all([",
  '    fetch("/admin/hub-notes").then(function(r){return r.json();}),',
  '    fetch("/admin/auto-clusters").then(function(r){return r.json();})',
  "  ]).then(function(results) {",
  "    hubNotes=results[0]||[];",
  "    autoClusters=results[1]||[];",
  "    var nodes=buildGraphNodes();",
  "    var cx=graphW/2,cy=graphH/2;",
  "    var mids=nodes.filter(function(n){return n.isTemplate||n.isCluster;});",
  "    var leaves=nodes.filter(function(n){return !n.isHub&&!n.isTemplate&&!n.isCluster;});",
  "    var scaleFactor=Math.max(1,Math.sqrt((mids.length*3+leaves.length)/18));",
  "    graphScale=scaleFactor;",
  "    var outerR=(Math.min(graphW,graphH)/2-24)*scaleFactor;",
  "    var midR=outerR*0.40;",
  "    var hub=nodes[0];",
  "    hub.x=cx;hub.y=cy;hub.vx=0;hub.vy=0;hub.r=15;hub.phase=0;",
  "    mids.forEach(function(n,i){",
  "      var angle=(i/Math.max(mids.length,1))*Math.PI*2;",
  "      n.x=cx+Math.cos(angle)*midR;n.y=cy+Math.sin(angle)*midR;",
  "      n.vx=0;n.vy=0;n.r=11;n.phase=Math.random()*Math.PI*2;",
  "    });",
  "    leaves.forEach(function(n,i){",
  "      var parent=entryParent(n,mids);",
  "      var baseAngle=parent?Math.atan2(parent.y-cy,parent.x-cx):(i/Math.max(leaves.length,1))*Math.PI*2;",
  "      var spread=mids.length>0?0.55:Math.PI*2;",
  "      var angle=baseAngle+(Math.random()-0.5)*spread;",
  "      var dist=outerR*(0.55+Math.random()*0.40);",
  "      n.x=cx+Math.cos(angle)*dist;n.y=cy+Math.sin(angle)*dist;",
  "      n.vx=0;n.vy=0;",
  "      n.r=Math.max(5,Math.min(10,5+Math.min(n.degree,5)));",
  "      n.phase=Math.random()*Math.PI*2;",
  "    });",
  "    var fitZoom=Math.max(0.05,Math.min(1,1/scaleFactor));",
  "    graphZoom=fitZoom;",
  "    graphPanX=graphW/2*(1-graphZoom);",
  "    graphPanY=graphH/2*(1-graphZoom);",
  "    graphZoomTarget=graphZoom;graphPanXTarget=graphPanX;graphPanYTarget=graphPanY;",
  "    graphNodes=nodes;",
  "    loadConstellations();",
  "    function loop(time){",
  "      stepPhysics(graphNodes);",
  "      if(graphResetting){",
  "        graphZoom+=(graphZoomTarget-graphZoom)*0.12;",
  "        graphPanX+=(graphPanXTarget-graphPanX)*0.12;",
  "        graphPanY+=(graphPanYTarget-graphPanY)*0.12;",
  "        if(Math.abs(graphZoomTarget-graphZoom)<0.002){",
  "          graphZoom=graphZoomTarget;graphPanX=graphPanXTarget;graphPanY=graphPanYTarget;graphResetting=false;",
  "        }",
  "      }",
  "      drawGraph(ctx,graphNodes,time);",
  "      graphAnimId=requestAnimationFrame(loop);",
  "    }",
  "    graphAnimId=requestAnimationFrame(loop);",
  "    function toWorld(cx,cy){return {x:(cx-graphPanX)/graphZoom,y:(cy-graphPanY)/graphZoom};}",
  "    function nodeAt(cx,cy){",
  "      var w=toWorld(cx,cy);",
  "      return graphNodes.slice().reverse().find(function(n){return Math.hypot(n.x-w.x,n.y-w.y)<=n.r+7;});",
  "    }",
  "    canvas.onwheel=function(e){",
  "      e.preventDefault();",
  "      graphResetting=false;",
  "      var rect=canvas.getBoundingClientRect();",
  "      var mx=e.clientX-rect.left, my=e.clientY-rect.top;",
  "      var factor=e.deltaY<0?1.12:0.89;",
  "      graphPanX=mx-(mx-graphPanX)*factor;",
  "      graphPanY=my-(my-graphPanY)*factor;",
  "      graphZoom=Math.max(0.05,Math.min(5,graphZoom*factor));",
  "      graphZoomTarget=graphZoom;graphPanXTarget=graphPanX;graphPanYTarget=graphPanY;",
  "    };",
    "    canvas.ondblclick=function(e){",
    "      e.preventDefault();",
    "      graphZoomTarget=fitZoom;",
    "      graphPanXTarget=graphW/2*(1-fitZoom);",
    "      graphPanYTarget=graphH/2*(1-fitZoom);",
    "      graphResetting=true;",
    "    };",
  "    canvas.onmousedown=function(e){",
  "      var rect=canvas.getBoundingClientRect();",
  "      var cx=e.clientX-rect.left,cy=e.clientY-rect.top;",
  "      var hit=nodeAt(cx,cy);",
  "      graphResetting=false;",
  "      if(hit){graphDragNode=hit;graphIsPanning=false;}",
  "      else{graphIsPanning=true;graphPanStartX=e.clientX-graphPanX;graphPanStartY=e.clientY-graphPanY;}",
  "      graphDragMoved=false;",
  "    };",
  "    canvas.onmousemove=function(e){",
  "      var rect=canvas.getBoundingClientRect();",
  "      var cx=e.clientX-rect.left,cy=e.clientY-rect.top;",
  "      if(graphIsPanning){",
  "        graphPanX=e.clientX-graphPanStartX;",
  "        graphPanY=e.clientY-graphPanStartY;",
  "        graphDragMoved=true;",
  "        canvas.style.cursor='grabbing';",
  "      } else if(graphDragNode){",
  "        var w=toWorld(cx,cy);",
  "        if(!graphDragNode.isHub){graphDragNode.x=w.x;graphDragNode.y=w.y;graphDragNode.vx=0;graphDragNode.vy=0;}",
  "        graphDragMoved=true;",
  "        canvas.style.cursor='grabbing';",
  "      } else {",
  "        var h=nodeAt(cx,cy);",
  "        hoveredNode=h||null;",
  "        canvas.style.cursor=h?'pointer':'grab';",
  "      }",
  "    };",
  "    canvas.onmouseleave=function(){hoveredNode=null;graphIsPanning=false;};",
  "    canvas.onmouseup=function(e){",
  "      var rect=canvas.getBoundingClientRect();",
  "      var cx=e.clientX-rect.left,cy=e.clientY-rect.top;",
  "      if(!graphDragMoved&&!graphIsPanning){",
  "        var hit=nodeAt(cx,cy);",
  '        var detail=document.getElementById("graphDetail");',
  "        if(!hit||hit.isHub||hit.isCluster||hit.isTemplate){",
  '          detail.classList.remove("open");',
  "        } else {",
  '          var tagClass=hit.source==="auto"?"source-tag auto":"source-tag";',
  '          detail.innerHTML="<div class=\\"know-meta\\"><span class=\\""+tagClass+"\\">"+( hit.source==="auto"?"auto":"manual")+"</span>"+',
  '            "<span style=\\"margin-left:8px;font-size:11px;color:#8E8E93;\\">"+hit.degree+" conexion"+(hit.degree===1?"":"es")+"</span></div>"+',
  '            "<div class=\\"know-content\\">"+escapeHtml(hit.content)+"</div>"+',
  '            "<div style=\\"display:flex;gap:8px;margin-top:8px;\\"><button class=\\"edit\\" onclick=\\"editKnowledge("+hit.id+",this)\\">Editar</button>"+',
  '            "<button class=\\"del\\" onclick=\\"deleteKnowledge("+hit.id+")\\">Borrar</button></div>";',
  '          detail.classList.add("open");',
  "        }",
  "      }",
  "      graphDragNode=null;graphIsPanning=false;",
  "    };",
  "  }).catch(function(){hubNotes=[];autoClusters=[];});",
  "}",
  "",
  'window.addEventListener("resize", function () { if (brainView === "graph") renderGraph(); });',
  "",
  "var allNotes = [];",
  "var openTabs = [];",
  "var activeTabId = null;",
  "",
  "function findNote(id) {",
  "  return allNotes.find(function (n) { return n.id === id; });",
  "}",
  "",
  "function findNoteByName(name) {",
  "  var n = name.trim().toLowerCase();",
  "  return allNotes.find(function (note) {",
  '    if ((note.title || "").trim().toLowerCase() === n) return true;',
  "    return (note.aliases || []).some(function (a) { return a.trim().toLowerCase() === n; });",
  "  });",
  "}",
  "",
  "function renderMarkdown(text) {",
  '  var html = escapeHtml(text || "");',
  '  html = html.replace(/\\[\\[([^\\]]+)\\]\\]/g, function (m, name) {',
  "    var target = findNoteByName(name);",
  '    var cls = target ? "wikilink" : "wikilink missing";',
  '    return "<a class=\\"" + cls + "\\" data-wikilink=\\"" + escapeHtml(name) + "\\">" + escapeHtml(name) + "</a>";',
  "  });",
  '  html = html.replace(/^### (.*)$/gm, "<h3>$1</h3>");',
  '  html = html.replace(/^## (.*)$/gm, "<h2>$1</h2>");',
  '  html = html.replace(/^# (.*)$/gm, "<h1>$1</h1>");',
  '  html = html.replace(/\\*\\*(.+?)\\*\\*/g, "<strong>$1</strong>");',
  '  html = html.replace(/^- (.*)$/gm, "<li>$1</li>");',
  '  html = html.replace(/(<li>.*<\\/li>)/gs, "<ul>$1</ul>");',
  '  html = html.replace(/\\n/g, "<br/>");',
  "  return html;",
  "}",
  "",
  "function handleWikilinkClick(name) {",
  "  var target = findNoteByName(name);",
  "  if (target) openNoteTab(target.id);",
  "}",
  "",
  'document.addEventListener("click", function (e) {',
  '  var link = e.target.closest && e.target.closest(".wikilink");',
  "  if (link) handleWikilinkClick(link.dataset.wikilink);",
  "});",
  "",
  "async function loadNotes() {",
  '  var res = await fetch("/admin/notes");',
  "  allNotes = await res.json();",
  "  renderNotesList();",
  "  renderTabs();",
  "  renderPanes();",
  "}",
  "",
  "function renderNotesList() {",
  '  var q = (document.getElementById("notesSearch").value || "").toLowerCase();',
  "  var filtered = allNotes.filter(function (n) {",
  '    return (n.title || "").toLowerCase().indexOf(q) !== -1 || (n.content || "").toLowerCase().indexOf(q) !== -1;',
  "  });",
  '  var list = document.getElementById("notesList");',
  '  list.innerHTML = "";',
  "  filtered.forEach(function (n) {",
  '    var div = document.createElement("div");',
  '    div.className = "ns-item" + (n.id === activeTabId ? " active" : "");',
  '    var titleLabel = (n.is_daily ? "📅 " : "") + (n.title || "Sin título");',
  '    div.innerHTML = "<div class=\\"ns-title\\">" + escapeHtml(titleLabel) + "</div>" +',
  '      "<div class=\\"ns-snippet\\">" + escapeHtml((n.content || "").slice(0, 40)) + "</div>";',
  '    div.title = "Clic para abrir";',
  "    div.onclick = function () { openNoteTab(n.id); };",
  "    list.appendChild(div);",
  "  });",
  "}",
  "",
  "function renderTabs() {",
  '  var tabsEl = document.getElementById("notesTabs");',
  '  tabsEl.innerHTML = "";',
  "  openTabs.forEach(function (id) {",
  "    var note = findNote(id);",
  "    if (!note) return;",
  '    var tab = document.createElement("div");',
  '    tab.className = "notes-tab" + (id === activeTabId ? " active" : "");',
  "    tab.onclick = function () { activeTabId = id; renderNotesList(); renderTabs(); renderPanes(); };",
  '    tab.innerHTML = escapeHtml(note.title || "Sin título") + " <span class=\\"tab-close\\" onclick=\\"closeTab(" + id + ", event)\\">×</span>";',
  "    tabsEl.appendChild(tab);",
  "  });",
  "}",
  "",
  "function closeTab(id, event) {",
  "  if (event) event.stopPropagation();",
  "  openTabs = openTabs.filter(function (t) { return t !== id; });",
  "  if (activeTabId === id) activeTabId = openTabs.length ? openTabs[openTabs.length - 1] : null;",
  "  renderNotesList();",
  "  renderTabs();",
  "  renderPanes();",
  "}",
  "",
  "function openNoteTab(id) {",
  "  if (openTabs.indexOf(id) === -1) openTabs.push(id);",
  "  activeTabId = id;",
  "  renderNotesList();",
  "  renderTabs();",
  "  renderPanes();",
  "}",
  "",
  "function buildPaneEl(note, isPreviewMode) {",
  '  var pane = document.createElement("div");',
  '  pane.className = "note-pane";',
  "",
  '  var toolbar = document.createElement("div");',
  '  toolbar.className = "ns-toolbar";',
  '  var btnPreview = document.createElement("button");',
  '  btnPreview.textContent = isPreviewMode ? "✏️ Editar" : "👁 Vista previa";',
  "  btnPreview.onclick = function () { note._preview = !isPreviewMode; renderPanes(); };",
  '  var btnSave = document.createElement("button");',
  '  btnSave.textContent = "💾 Guardar";',
  "  btnSave.onclick = function () { saveNote(note.id, pane); };",
  '  var btnVersions = document.createElement("button");',
  '  btnVersions.textContent = "🕘 Historial";',
  "  btnVersions.onclick = function () { showVersions(note.id); };",
  '  var btnDelete = document.createElement("button");',
  '  btnDelete.textContent = "🗑 Borrar";',
  "  btnDelete.onclick = function () { deleteNote(note.id); };",
  "  toolbar.appendChild(btnPreview);",
  "  toolbar.appendChild(btnSave);",
  "  toolbar.appendChild(btnVersions);",
  "  toolbar.appendChild(btnDelete);",
  "  pane.appendChild(toolbar);",
  "",
  '  var titleInput = document.createElement("input");',
  '  titleInput.className = "ns-title-input";',
  '  titleInput.value = note.title || "";',
  '  titleInput.placeholder = "Título";',
  "  pane.appendChild(titleInput);",
  "",
  '  var tagsInput = document.createElement("input");',
  '  tagsInput.className = "ns-tags-input";',
  '  tagsInput.value = (note.tags || []).join(", ");',
  '  tagsInput.placeholder = "#tags separados por coma";',
  "  pane.appendChild(tagsInput);",
  "",
  "  if (isPreviewMode) {",
  '    var preview = document.createElement("div");',
  '    preview.className = "ns-preview";',
  "    preview.innerHTML = renderMarkdown(note.content);",
  "    pane.appendChild(preview);",
  "  } else {",
  '    var editor = document.createElement("textarea");',
  '    editor.className = "ns-editor";',
  "    editor.value = note.content || \"\";",
  "    pane.appendChild(editor);",
  "  }",
  "",
  '  var backlinksWrap = document.createElement("div");',
  '  backlinksWrap.className = "ns-backlinks";',
  '  var blTitle = document.createElement("div");',
  '  blTitle.textContent = "Backlinks:";',
  "  backlinksWrap.appendChild(blTitle);",
  "  (note.backlinks || []).forEach(function (bl) {",
  '    var blItem = document.createElement("div");',
  '    blItem.className = "bl-item";',
  '    blItem.textContent = bl.title || ("Nota #" + bl.id);',
  "    blItem.onclick = function () { openNoteTab(bl.id); };",
  "    backlinksWrap.appendChild(blItem);",
  "  });",
  "  if (!note.backlinks || note.backlinks.length === 0) {",
  '    var none = document.createElement("div");',
  '    none.textContent = "Ninguno";',
  '    none.style.color = "#C7C7CC";',
  "    backlinksWrap.appendChild(none);",
  "  }",
  "  pane.appendChild(backlinksWrap);",
  "",
  "  pane._titleInput = titleInput;",
  "  pane._tagsInput = tagsInput;",
  "  pane._noteId = note.id;",
  "  return pane;",
  "}",
  "",
  "function renderPanes() {",
  '  var panesEl = document.getElementById("notesPanes");',
  '  panesEl.innerHTML = "";',
  "  if (!activeTabId) {",
  '    var empty = document.createElement("div");',
  '    empty.className = "ns-empty";',
  '    empty.textContent = "Selecciona o crea una nota para empezar";',
  "    panesEl.appendChild(empty);",
  "    return;",
  "  }",
  "  var note1 = findNote(activeTabId);",
  "  if (note1) panesEl.appendChild(buildPaneEl(note1, !!note1._preview));",
  "}",
  "",
  "async function saveNote(id, pane) {",
  "  var title = pane._titleInput.value.trim();",
  '  var tags = pane._tagsInput.value.split(",").map(function (t) { return t.trim(); }).filter(Boolean);',
  '  var editor = pane.querySelector(".ns-editor");',
  "  var content = editor ? editor.value : findNote(id).content;",
  '  await fetch("/admin/notes/" + id, {',
  '    method: "PUT",',
  '    headers: { "Content-Type": "application/json" },',
  "    body: JSON.stringify({ title: title, content: content, tags: tags }),",
  "  });",
  "  await loadNotes();",
  "}",
  "",
  "async function deleteNote(id) {",
  '  await fetch("/admin/notes/" + id, { method: "DELETE" });',
  "  closeTab(id, null);",
  "  await loadNotes();",
  "}",
  "",
  "async function createNewNote() {",
  '  var res = await fetch("/admin/notes", {',
  '    method: "POST",',
  '    headers: { "Content-Type": "application/json" },',
  '    body: JSON.stringify({ title: "Nueva nota", content: "" }),',
  "  });",
  "  var note = await res.json();",
  "  await loadNotes();",
  "  openNoteTab(note.id);",
  "}",
  "",
  "async function openDailyNote() {",
  '  var res = await fetch("/admin/notes/daily", { method: "POST" });',
  "  var note = await res.json();",
  "  await loadNotes();",
  "  openNoteTab(note.id);",
  "}",
  "",
  "async function showVersions(id) {",
  '  var res = await fetch("/admin/notes/" + id + "/versions");',
  "  var versions = await res.json();",
  '  var body = document.getElementById("versionsModalBody");',
  '  var html = "<h3>Historial de versiones</h3>";',
  "  if (versions.length === 0) {",
  '    html += "<div class=\\"value\\">Sin versiones anteriores</div>";',
  "  } else {",
  "    versions.forEach(function (v) {",
  '      html += "<div class=\\"ns-version-item\\" onclick=\\"restoreVersion(" + id + ", " + v.id + ")\\">" +',
  '        escapeHtml(formatDate(v.created_at)) + " — " + escapeHtml((v.content || "").slice(0, 50)) + "</div>";',
  "    });",
  "  }",
  '  html += "<button class=\\"close-btn\\" onclick=\\"closeVersionsModal()\\">Cerrar</button>";',
  "  body.innerHTML = html;",
  '  document.getElementById("versionsModal").classList.add("open");',
  "}",
  "",
  "function closeVersionsModal() {",
  '  document.getElementById("versionsModal").classList.remove("open");',
  "}",
  "",
  "async function restoreVersion(id, versionId) {",
  '  await fetch("/admin/notes/" + id + "/restore/" + versionId, { method: "POST" });',
  "  closeVersionsModal();",
  "  await loadNotes();",
  "  renderPanes();",
  "}",
  "",
  "async function openTemplatesModal(message) {",
  '  var res = await fetch("/admin/templates");',
  "  var templates = await res.json();",
  '  var body = document.getElementById("templatesModalBody");',
  '  var html = "<h3>Plantillas reutilizables</h3>";',
  '  html += "<div style=\\"font-size:12px; color:#6E6E73; margin-bottom:10px;\\">Crea una plantilla una vez y úsala como punto de partida para notas nuevas (la plantilla original no se modifica).</div>";',
  "  if (message) {",
  '    html += "<div style=\\"background:rgba(52,199,89,0.12); color:#1B8A3D; padding:6px 10px; border-radius:8px; font-size:12px; margin-bottom:10px;\\">" + escapeHtml(message) + "</div>";',
  "  }",
  "  if (templates.length === 0) {",
  '    html += "<div class=\\"value\\">Sin plantillas todavía</div>";',
  "  } else {",
  "    templates.forEach(function (t) {",
  '      html += "<div class=\\"tpl-item\\"><span class=\\"tpl-name\\">" + escapeHtml(t.name) + "</span>" +',
  '        "<button class=\\"tpl-use\\" onclick=\\"useTemplate(" + t.id + ")\\">Usar</button>" +',
  '        "<button onclick=\\"deleteTemplateAndRefresh(" + t.id + ")\\">Borrar</button></div>";',
  "    });",
  "  }",
  '  html += "<input class=\\"tpl-input\\" id=\\"newTplName\\" placeholder=\\"Nombre de la plantilla\\" />";',
  '  html += "<textarea class=\\"tpl-input\\" id=\\"newTplContent\\" rows=\\"4\\" placeholder=\\"Contenido de la plantilla\\"></textarea>";',
  '  html += "<button class=\\"close-btn\\" style=\\"background:#0A84FF; margin-top:8px;\\" onclick=\\"saveNewTemplate()\\">Guardar plantilla</button>";',
  '  html += "<button class=\\"close-btn\\" onclick=\\"closeTemplatesModal()\\">Cerrar</button>";',
  "  body.innerHTML = html;",
  '  document.getElementById("templatesModal").classList.add("open");',
  "}",
  "",
  "function closeTemplatesModal() {",
  '  document.getElementById("templatesModal").classList.remove("open");',
  "}",
  "",
  "async function saveNewTemplate() {",
  '  var name = document.getElementById("newTplName").value.trim();',
  '  var content = document.getElementById("newTplContent").value;',
  "  if (!name || !content) return;",
  '  await fetch("/admin/templates", {',
  '    method: "POST",',
  '    headers: { "Content-Type": "application/json" },',
  "    body: JSON.stringify({ name: name, content: content }),",
  "  });",
  '  await openTemplatesModal("✓ Plantilla guardada");',
  "}",
  "",
  "async function deleteTemplateAndRefresh(id) {",
  '  await fetch("/admin/templates/" + id, { method: "DELETE" });',
  '  await openTemplatesModal("✓ Plantilla borrada");',
  "}",
  "",
  "async function useTemplate(id) {",
  '  var res = await fetch("/admin/templates");',
  "  var templates = await res.json();",
  "  var tpl = templates.find(function (t) { return t.id === id; });",
  "  if (!tpl) return;",
  '  var res2 = await fetch("/admin/notes", {',
  '    method: "POST",',
  '    headers: { "Content-Type": "application/json" },',
  "    body: JSON.stringify({ title: tpl.name, content: tpl.content }),",
  "  });",
  "  var note = await res2.json();",
  "  closeTemplatesModal();",
  "  await loadNotes();",
  "  openNoteTab(note.id);",
  "}",
  "",
  "var FILE_TYPE_ICON = { pdf: \"📕\", word: \"📘\", excel: \"📗\", image: \"🖼️\", vcf: \"👤\" };",
  "var FILE_TYPE_LABEL = { pdf: \"PDF\", word: \"Word\", excel: \"Excel\", image: \"Imagen\", vcf: \"Contacto VCF\" };",
  "",
  "async function loadFiles() {",
  '  var res = await fetch("/admin/files");',
  "  var fileRows = await res.json();",
  '  var list = document.getElementById("filesList");',
  '  list.innerHTML = "";',
  "  if (fileRows.length === 0) {",
  '    list.innerHTML = "<div class=\\"ns-empty\\">Sin archivos importados todavía</div>";',
  "    return;",
  "  }",
  "  fileRows.forEach(function (f) {",
  '    var div = document.createElement("div");',
  '    div.className = "file-item";',
  '    var icon = FILE_TYPE_ICON[f.file_type] || "📄";',
  '    var typeLabel = FILE_TYPE_LABEL[f.file_type] || f.file_type;',
  '    var statusLabel = f.status === "processing" ? "Procesando…" : (f.status === "error" ? "Error" : "Listo");',
  '    var statusClass = f.status === "error" ? "file-status error" : (f.status === "processing" ? "file-status processing" : "file-status done");',
  '    div.innerHTML = "<div class=\\"file-icon\\">" + icon + "</div>" +',
  '      "<div class=\\"file-info\\"><div class=\\"file-name\\">" + escapeHtml(f.original_name) + "</div>" +',
  '      "<div class=\\"file-meta\\">" + typeLabel + " · <span class=\\"" + statusClass + "\\">" + statusLabel + "</span></div></div>";',
  '    var actions = document.createElement("div");',
  '    actions.className = "file-actions";',
  "    if (f.note_id) {",
  '      var openBtn = document.createElement("button");',
  '      openBtn.textContent = "Ver nota";',
  "      openBtn.onclick = function () {",
  '        setBrainView("notes");',
  "        setTimeout(function () { openNoteTab(f.note_id); }, 50);",
  "      };",
  "      actions.appendChild(openBtn);",
  "    }",
  '    var delBtn = document.createElement("button");',
  '    delBtn.className = "del";',
  '    delBtn.textContent = "Borrar";',
  "    delBtn.onclick = function () { deleteFileAndRefresh(f.id); };",
  "    actions.appendChild(delBtn);",
  "    div.appendChild(actions);",
  "    list.appendChild(div);",
  "  });",
  "}",
  "",
  "async function deleteFileAndRefresh(id) {",
  '  await fetch("/admin/files/" + id, { method: "DELETE" });',
  "  loadFiles();",
  "}",
  "",
  "async function uploadFiles(fileList) {",
  '  var statusEl = document.getElementById("filesUploadStatus");',
  "  for (var i = 0; i < fileList.length; i++) {",
  "    var file = fileList[i];",
  '    statusEl.textContent = "Subiendo " + file.name + "…";',
  "    var formData = new FormData();",
  '    formData.append("file", file);',
  "    try {",
  '      var res = await fetch("/admin/files/upload", { method: "POST", body: formData });',
  "      if (!res.ok) {",
  "        var err = await res.json();",
  '        statusEl.textContent = "Error con " + file.name + ": " + (err.error || "no se pudo subir");',
  "        continue;",
  "      }",
  "    } catch (e) {",
  '      statusEl.textContent = "Error subiendo " + file.name;',
  "      continue;",
  "    }",
  "  }",
  '  statusEl.textContent = "";',
  "  loadFiles();",
  "}",
  "",
  '(function setupFilesDropzone() {',
  '  var zone = document.getElementById("filesDropzone");',
  '  var input = document.getElementById("filesInput");',
  "  zone.onclick = function () { input.click(); };",
  "  input.onchange = function () {",
  "    if (input.files.length) uploadFiles(input.files);",
  '    input.value = "";',
  "  };",
  "  zone.ondragover = function (e) {",
  "    e.preventDefault();",
  '    zone.classList.add("dragover");',
  "  };",
  "  zone.ondragleave = function () {",
  '    zone.classList.remove("dragover");',
  "  };",
  "  zone.ondrop = function (e) {",
  "    e.preventDefault();",
  '    zone.classList.remove("dragover");',
  "    if (e.dataTransfer.files.length) uploadFiles(e.dataTransfer.files);",
  "  };",
  "})();",
  "",
  "loadMessages();",
  "loadKnowledge();",
  "</script>",
  "</body>",
  "</html>",
].join("\n");

module.exports = router;
